"""math-quiz's data layer: session history, the in-progress draft, "flag for
review" bookmarks, the suite-wide mistake journal, confidence calibration and
this app's own settings.

Since the migration to ``common/`` this module is an **adapter**, not an
implementation.  The shared stores live in one place for all ten apps:

``common.datadir``  where the files are (``QUANTUM_STUDY_DATA_DIR``, resolved
                    at call time — no frozen module constants any more).
``common.journal``  ``mistakes.json`` / ``confidence.json``: locked,
                    atomic, other apps' rows preserved verbatim, and the
                    growth cap trims **only our own** rows.
``common.flags``    ``math_flagged.json``: atomic, rewritten from the raw
                    list so a row we do not understand is never deleted.
``common.schema``   a version sidecar, forward migration and a rotating
                    backup for every file this app writes.

What stays here is what is genuinely math-quiz's own: the *shape* of a session
record, the SRS weighting, the two id functions (a question generated by
Claude has no identity except a hash of its text), and the signatures the
screens already call — every public name below behaves as it did, so the UI,
``coach.py`` and ``dashboard.py`` are untouched.
"""

from __future__ import annotations

import datetime
import hashlib
import math
import time
from pathlib import Path

import common_path  # noqa: F401  (puts the repo root on sys.path)

from common import datadir, flags, journal, schema
from common.jsonio import read_json_dict

from core.models import SessionStats, Question

#: This app's directory name — the ``app`` field of every row we write, and
#: what ``coach.py`` / ``dashboard.py`` group by.
APP = "math-quiz"
_APP_DIR_NAME = APP                  # the name the app used before the migration

_FLAG_LABEL_MAX = flags.LABEL_MAX

# Time-based SRS: 14-day half-life.  A session saved 14 days ago contributes
# half the weight of one saved today; 28 days ago → one quarter, etc.
_HALF_LIFE_DAYS = 14.0

#: Schema kind for ``math_draft.json``.  The shared kinds cover mistakes,
#: confidence, flagged, history, settings and schedule; the interrupted-session
#: draft is this app's own file, so it registers its own kind.  ``replace=True``
#: because ``tests/test_journal_concurrency.py`` loads this module twice, by
#: path, in one process.
DRAFT_KIND = "math-quiz-draft"
schema.register(
    schema.FileSchema(DRAFT_KIND,
                      description="math-quiz interrupted-session draft "
                                  "(math_draft.json)"),
    replace=True,
)


# ── Where the files are (resolved at call time, never cached) ────────────────

def data_dir() -> Path:
    """The suite data directory — ``QUANTUM_STUDY_DATA_DIR`` or the default."""
    return datadir.data_dir()


def history_file() -> Path:
    return datadir.app_file(APP, "history")          # math_history.json


def draft_file() -> Path:
    return datadir.app_file(APP, "draft")            # math_draft.json


def flagged_file() -> Path:
    return flags.flagged_path(APP)                   # math_flagged.json


def settings_file() -> Path:
    return datadir.app_file(APP, "settings")         # math_settings.json


def mistakes_file() -> Path:
    return journal.mistakes_path()                   # mistakes.json (shared)


def confidence_file() -> Path:
    return journal.confidence_path()                 # confidence.json (shared)


# ── Session history ───────────────────────────────────────────────────────────
#
# math_history.json is load-bearing: coach.py and dashboard.py parse it.  Its
# shape is unchanged by the migration; only the writer is now versioned and
# backed up.

def save_session(stats: SessionStats) -> None:
    history = _load_raw()
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
    history.append({
        "date": str(datetime.date.today()),
        "timestamp": timestamp,
        "answered": stats.answered,
        "average_score": round(stats.average_score, 2),
        "records": [
            {
                "question_id": r.question_id,
                "subject": r.question.subject,
                "topic": r.question.topic,
                "score": r.evaluation.score,
                "elapsed_seconds": r.elapsed_seconds,
                "timestamp": timestamp,
            }
            for r in stats.history
        ],
    })
    schema.save_versioned(history_file(), history, "history")
    clear_draft()


def save_draft(stats: SessionStats) -> None:
    """Overwrite the in-progress draft so a crash doesn't lose answered questions."""
    data = {
        "date": str(datetime.date.today()),
        "answered": stats.answered,
        "skipped": stats.skipped,
        "average_score": round(stats.average_score, 2),
        "questions": [
            {
                "subject": r.question.subject,
                "topic": r.question.topic,
                "difficulty": r.question.difficulty,
                "type": r.question.question_type,
                "question": r.question.text,
                "answer": r.user_answer,
                "score": r.evaluation.score,
                "verdict": r.evaluation.verdict,
                "feedback": r.evaluation.feedback,
                "model_answer": r.evaluation.model_answer,
            }
            for r in stats.history
        ],
    }
    schema.save_versioned(draft_file(), data, DRAFT_KIND)


def load_draft() -> dict:
    """The saved draft, migrated forward; ``{}`` when there is none."""
    return schema.load_versioned(draft_file(), DRAFT_KIND, reader=read_json_dict)


def clear_draft() -> None:
    path = draft_file()
    if path.exists():
        path.unlink()


def has_draft() -> bool:
    return draft_file().exists()


def avg_scores_by_subject() -> dict[str, float]:
    """Time-decayed average score per subject across all saved sessions."""
    return _weighted_averages(key_fn=lambda r: r.get("subject", ""))


def avg_scores_by_topic() -> dict[str, float]:
    """Time-decayed average score per subject::topic key."""
    return _weighted_averages(
        key_fn=lambda r: f"{r.get('subject','')}::{r.get('topic','')}"
    )


def question_score_weights() -> dict[str, float]:
    """Return per-question SRS sampling weights keyed by question_id.

    Weight formula (14-day half-life):
        weight   = exp(-days * log(2) / 14.0)
        avg_score = weighted_sum / weighted_count
        result[qid] = max(0.5, 2.0 - avg_score * 0.15)

    Unseen questions receive weight 1.25.
    """
    now = datetime.datetime.now(datetime.timezone.utc)
    buckets: dict[str, list[tuple[float, int]]] = {}

    for session in _load_raw():
        for r in session.get("records", []):
            qid = r.get("question_id")
            if not qid:
                continue
            w = _record_weight(r, session, now)
            buckets.setdefault(qid, []).append((w, r.get("score", 0)))

    result: dict[str, float] = {}
    for qid, pairs in buckets.items():
        total_w = sum(w for w, _ in pairs)
        avg_score = sum(w * s for w, s in pairs) / total_w if total_w else 0.0
        result[qid] = max(0.5, 2.0 - avg_score * 0.15)
    return result


# ── Flag for review ───────────────────────────────────────────────────────────
#
# math_flagged.json follows the suite-wide schema:
#   {"id": str, "label": str, "category": str, "app": "math-quiz",
#    "timestamp": epoch float}
# The store is common.flags; what is app-specific is how a generated question
# gets a stable id and a readable label.  Flagging is a toggle.

def flag_id_for(question: Question) -> str:
    """Stable id for a generated question: the SRS topic key plus a short
    hash of the question text, so two questions on one topic stay distinct
    while the topic remains readable in the id."""
    digest = hashlib.sha1(question.text.strip().encode("utf-8")).hexdigest()[:8]
    return f"{question.subject}::{question.topic}#{digest}"


def flag_label_for(question: Question) -> str:
    """Question text collapsed to one line and truncated to 80 characters."""
    return flags.make_label(question.text, _FLAG_LABEL_MAX)


def make_flag_entry(question: Question) -> dict:
    return {
        "id":        flag_id_for(question),
        "label":     flag_label_for(question),
        "category":  question.subject,
        "app":       APP,
        "timestamp": time.time(),
    }


def load_flagged() -> list[dict]:
    """Flagged entries (oldest first) in the suite-wide shape."""
    return flags.load_flagged(flagged_file(), APP)


def save_flagged(entries: list[dict]) -> bool:
    """Rewrite the flag file atomically, under the lock, with a version stamp."""
    return flags.save_flagged(flagged_file(), entries, APP)


def flagged_ids() -> set[str]:
    return flags.flagged_ids(flagged_file(), APP)


def is_flagged(question_or_id: Question | str) -> bool:
    return flags.is_flagged(flagged_file(), _coerce_flag_id(question_or_id), APP)


def toggle_flag(question_or_entry: Question | dict) -> bool:
    """Flag the question if it is not flagged, unflag it otherwise.

    Accepts a Question or a prepared entry dict. Returns the new state
    (True = now flagged). Raises ValueError for a dict without an ``id``.
    """
    if isinstance(question_or_entry, Question):
        entry = make_flag_entry(question_or_entry)
    else:
        entry = dict(question_or_entry)
    flag_id = str(entry.get("id") or "").strip()
    if not flag_id:
        raise ValueError("flag entry needs an 'id'")
    return flags.toggle_flag(
        flagged_file(), flag_id,
        label=str(entry.get("label") or ""),
        category=str(entry.get("category") or ""),
        app=APP,
    )


def unflag(question_or_id: Question | str) -> bool:
    """Remove a flagged entry. Returns True if something was removed."""
    return flags.unflag(flagged_file(), _coerce_flag_id(question_or_id), app=APP)


def _coerce_flag_id(question_or_id: Question | str) -> str:
    if isinstance(question_or_id, Question):
        return flag_id_for(question_or_id)
    return str(question_or_id)


# ── Mistake journal ───────────────────────────────────────────────────────────
#
# mistakes.json is the suite-wide journal; common.journal owns the reads and
# writes (locked, atomic, foreign rows verbatim, our own rows trimmed).  What
# is app-specific is the item id — a question Claude generated has no identity
# except a hash of its subject and text — and the Question-shaped signatures
# the screens call.
#
# A wrong answer is logged immediately with cause=None so nothing is lost when
# the user skips the "what went wrong?" row; choosing a cause updates that same
# entry.  Answering the same item correctly later flips resolved to True.

MISTAKE_CAUSES: tuple[str, ...] = journal.MISTAKE_CAUSES

#: Value used by :func:`mistake_cause_counts` for entries with ``cause=None``.
UNCATEGORISED = journal.UNCATEGORISED

#: Cap on the one-line fields (question, answers).  The UI's note field uses
#: :data:`NOTE_FIELD_MAX`, which is larger because a note is prose.
TEXT_FIELD_MAX = journal.TEXT_MAX
NOTE_FIELD_MAX = journal.NOTE_MAX

#: Growth cap, applied to **this app's** rows only (never another app's).
_MISTAKES_MAX = journal.MISTAKES_MAX

clip_text = journal.clip_text
clip_note = journal.clip_note


def mistake_id_for(question: Question) -> str:
    """Stable item id: SHA-1 of ``subject`` + whitespace-collapsed question text.

    The same question asked again (even re-wrapped by the model) maps to the
    same id, which is what lets a later correct answer resolve it.
    """
    text = " ".join(question.text.split())
    basis = f"{question.subject}\n{text}"
    return hashlib.sha1(basis.encode("utf-8")).hexdigest()[:16]


def coerce_cause(cause: str | None) -> str | None:
    """A recognised cause code, else ``None`` ("logged, not yet categorised").

    Never raises: an unrecognised value must not cost us the mistake itself.
    """
    return journal.normalise_cause(cause)


def make_mistake_entry(
    question: Question,
    your_answer: str,
    correct_answer: str,
    cause: str | None = None,
    note: str = "",
    timestamp: float | None = None,
    resolved: bool = False,
) -> dict:
    """Build a journal entry (pure: no I/O, no Qt)."""
    return journal.make_mistake_entry(
        mistake_id_for(question), APP,
        category=question.subject,
        question=question.text,
        your_answer=your_answer,
        correct_answer=correct_answer,
        cause=cause,
        note=note,
        timestamp=timestamp,
        resolved=resolved,
    )


def load_mistakes() -> list[dict]:
    """Every app's entries, oldest first. Rows with no id are skipped."""
    return [e for e in journal.load_mistakes() if e.get("id")]


def load_app_mistakes() -> list[dict]:
    """Only this app's entries (``app == "math-quiz"``), oldest first."""
    return [e for e in journal.load_mistakes(APP) if e.get("id")]


def save_mistakes(entries: list[dict]) -> bool:
    """Rewrite the journal: our rows as given, every other app's row verbatim."""
    return journal.save_mistakes(entries, APP)


def log_mistake(
    question: Question,
    your_answer: str,
    correct_answer: str,
    cause: str | None = None,
    note: str = "",
) -> dict:
    """Record a wrong answer and return the stored entry.

    Repeats are **appended, not merged**: three slips on the same item are
    three rows.  ``dashboard.load_mistakes`` says why — "a genuine second miss
    of the same item keeps its own entry, because repetition is exactly the
    signal" — and merging destroyed the count ``coach --mistakes`` reports.
    """
    entry = make_mistake_entry(question, your_answer, correct_answer, cause, note)
    return journal.log_mistake(entry)


_UNSET = object()


def update_mistake(entry_id: str, cause: object = _UNSET,
                   note: object = _UNSET) -> dict | None:
    """Set the cause and/or note of the newest entry for ``entry_id``.

    Returns the updated entry, or ``None`` when nothing matches.  Passing
    ``cause=None`` explicitly clears a previously chosen cause; omitting it
    leaves whatever cause is already stored alone, which is what the feedback
    screen needs when only the note changed.
    """
    target = str(entry_id)
    # Re-entrant: common.journal takes the same lock again inside
    # set_mistake_cause.  Holding it across the read makes the
    # read-then-write below atomic instead of a race.
    with journal.lock(journal.mistakes_path()):
        if cause is _UNSET:
            existing = _newest_entry(target)
            if existing is None:
                return None
            new_cause: object = existing.get("cause")
        else:
            new_cause = cause
        new_note = None if note is _UNSET else clip_note(note)
        return journal.set_mistake_cause(target, new_cause, new_note, app=APP)


def resolve_mistake(question_or_id: Question | str) -> bool:
    """Mark this app's open entries for the item as resolved. True if any changed."""
    target = (mistake_id_for(question_or_id)
              if isinstance(question_or_id, Question) else str(question_or_id))
    return journal.resolve_mistakes(target, APP) > 0


def mistake_cause_counts(include_resolved: bool = False) -> dict[str, int]:
    """Count this app's mistakes per cause (``None`` counted as ``uncategorised``)."""
    return journal.cause_counts(APP, include_resolved=include_resolved,
                                entries=load_app_mistakes())


def _newest_entry(entry_id: str) -> dict | None:
    """This app's newest row for *entry_id* — unresolved first, else any.

    Mirrors the row :func:`common.journal.set_mistake_cause` will edit, so the
    cause read here is the cause written back.
    """
    rows = [e for e in journal.mistakes_for(entry_id, APP)]
    if not rows:
        return None
    open_rows = [e for e in rows if not e.get("resolved")]
    return (open_rows or rows)[-1]


# ── Confidence calibration ────────────────────────────────────────────────────
#
# confidence.json is the suite-wide calibration log, owned by common.journal.
# 1=guessing, 2=unsure, 3=fairly sure, 4=certain.  Rated BEFORE the answer is
# graded, so it cannot be hindsight; the pairing is written once the grade
# arrives.  It exists to surface CONFIDENTLY WRONG topics — the unknown
# unknowns that sink exams.

CONFIDENCE_LABELS: dict[int, str] = journal.CONFIDENCE_LABELS
CONFIDENCE_LEVELS: tuple[int, ...] = journal.CONFIDENCE_LEVELS
CONFIDENCE_MIN = min(CONFIDENCE_LEVELS)
CONFIDENCE_MAX = max(CONFIDENCE_LEVELS)
CONFIDENT_LEVEL = journal.CONFIDENT_LEVEL

#: Growth cap for this app's calibration rows.
_CONFIDENCE_MAX_ROWS = journal.CONFIDENCE_MAX


def coerce_confidence(confidence: object) -> int | None:
    """A rating in 1–4, or ``None`` when the strip was skipped or unusable.

    ``None`` records nothing rather than inventing a rating the learner never
    gave (bools are rejected: ``True`` is not level 1).
    """
    return journal.coerce_confidence(confidence)


def make_confidence_entry(
    item_id: str,
    category: str,
    confidence: int,
    correct: bool,
    timestamp: float | None = None,
) -> dict:
    """Build a calibration row (pure: no I/O, no Qt)."""
    return journal.make_confidence_entry(item_id, APP, category, confidence,
                                         correct, timestamp)


def load_confidence() -> list[dict]:
    """Every app's calibration rows, oldest first. Rows with no id are skipped."""
    return [e for e in journal.load_confidence() if e.get("id")]


def save_confidence(entries: list[dict]) -> bool:
    """Rewrite calibration: our rows as given, every other app's row verbatim."""
    return journal.save_confidence(entries, APP)


def log_confidence(question: Question, confidence: int,
                   correct: bool) -> dict | None:
    """Append one confidence/outcome pairing and return it.

    A rating outside 1–4 records nothing and returns ``None``.
    """
    return journal.log_confidence(mistake_id_for(question), APP,
                                  question.subject, confidence, correct)


def confidence_accuracy() -> dict[int, dict[str, int]]:
    """``{level: {"total": n, "correct": c}}`` for this app's rows."""
    return journal.calibration_summary(APP)


def confidently_wrong_counts(min_confidence: int = CONFIDENT_LEVEL) -> dict[str, int]:
    """Per-category count of "sure and wrong" answers — the unknown unknowns."""
    return journal.confidently_wrong_by_category(APP,
                                                 min_confidence=min_confidence)


# ── App settings ──────────────────────────────────────────────────────────────
#
# math_settings.json holds this app's own preferences.  Today it stores one key:
#   {"confidence_prompt": bool}

_SETTINGS_DEFAULTS: dict = {"confidence_prompt": True}


def load_settings() -> dict:
    """App settings merged over the defaults; corrupt files fall back to defaults."""
    settings = dict(_SETTINGS_DEFAULTS)
    raw = schema.load_versioned(settings_file(), "settings",
                                reader=read_json_dict)
    if isinstance(raw, dict):
        settings.update(raw)
    return settings


def save_settings(settings: dict) -> None:
    schema.save_versioned(settings_file(), dict(settings), "settings")


def confidence_prompt_enabled() -> bool:
    """Whether to show the pre-answer confidence strip (opt-out is remembered)."""
    return bool(load_settings().get("confidence_prompt", True))


def set_confidence_prompt_enabled(enabled: bool) -> None:
    settings = load_settings()
    settings["confidence_prompt"] = bool(enabled)
    save_settings(settings)


# ── Internals ─────────────────────────────────────────────────────────────────

def _record_weight(r: dict, session: dict,
                   now: datetime.datetime) -> float:
    """Compute time-based weight for a single record using 14-day half-life."""
    ts_str = r.get("timestamp") or session.get("timestamp")
    if ts_str:
        try:
            ts = datetime.datetime.fromisoformat(ts_str)
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=datetime.timezone.utc)
            days = (now - ts).total_seconds() / 86400.0
        except Exception:
            days = 0.0
    else:
        try:
            d = datetime.date.fromisoformat(session.get("date", ""))
            days = (now.date() - d).days
        except Exception:
            days = 0.0
    return math.exp(-days * math.log(2) / _HALF_LIFE_DAYS)


def _weighted_averages(key_fn) -> dict[str, float]:
    """Build a time-decayed weighted average score per key."""
    now = datetime.datetime.now(datetime.timezone.utc)
    buckets: dict[str, list[tuple[float, int]]] = {}

    for session in _load_raw():
        for r in session.get("records", []):
            key = key_fn(r)
            if not key or key.startswith("::"):
                continue
            score = r.get("score", 0)
            weight = _record_weight(r, session, now)
            buckets.setdefault(key, []).append((weight, score))

    return {
        k: sum(w * s for w, s in pairs) / sum(w for w, _ in pairs)
        for k, pairs in buckets.items()
    }


def _load_raw() -> list[dict]:
    """Every saved session, migrated forward; a corrupt file reads as empty."""
    return [s for s in schema.load_versioned(history_file(), "history")
            if isinstance(s, dict)]
