"""Card: gate_MS_gate"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='gate_MS_gate',
    category='Gate Unitaries',
    front='Mølmer-Sørensen (MS) gate',
    back='MS(θ) = exp(−iθXX/2): a maximally entangling gate native to trapped-ion hardware, generated by the shared motional mode.  At θ=π/2 it is equivalent to a maximally entangling XX rotation.',
)
