"""Problem: qec_stabilizer_422 — constructing the [[4,2,2]] stabilizer code.

All commutation/anticommutation claims verified numerically with 16x16 matrices.
"""
from __future__ import annotations
from core.models import Problem, Part

PROBLEM = Problem(
    id="qec_stabilizer_422",
    topic="Error Correction",
    title="Constructing the [[4,2,2]] Stabilizer Code",
    statement=(
        "Consider four qubits with the stabilizer group S = ⟨S₁, S₂⟩ generated by\n\n"
        "    S₁ = X₁X₂X₃X₄ ,   S₂ = Z₁Z₂Z₃Z₄ .\n\n"
        "The code space is the simultaneous +1 eigenspace of S₁ and S₂. This is the "
        "smallest error-DETECTING code for arbitrary single-qubit errors, and a "
        "building block of many fault-tolerant schemes."
    ),
    parts=[
        Part(
            part_id="a",
            prompt=(
                "Verify that S₁ and S₂ commute and are independent, and determine the "
                "number of logical qubits k and the code-space dimension. State the "
                "general rule for n physical qubits and r independent stabilizer "
                "generators."
            ),
            points=3,
            rubric=[
                "Commutation: X and Z anticommute on each of the 4 shared qubits; "
                "(−1)⁴ = +1, so S₁S₂ = S₂S₁ (general rule: Pauli strings commute iff "
                "they anticommute on an even number of positions).",
                "Independence: neither generator is the identity or a product of the "
                "other(s) (S₁ ≠ ±S₂, S₁ ≠ I), and −I ∉ S.",
                "Rule: each independent generator halves the dimension: "
                "dim = 2ⁿ/2ʳ = 2^{n−r}; here 2⁴/2² = 4, so k = n − r = 2 logical qubits.",
            ],
            model_solution=(
                "On each qubit i, the factors Xᵢ and Zᵢ anticommute; commuting S₁ past "
                "S₂ picks up (−1) for each of the 4 overlapping anticommuting positions: "
                "(−1)⁴ = +1, hence [S₁, S₂] = 0 (verified numerically). They are "
                "independent (S₂ is not ±S₁ or I) and generate a group not containing "
                "−I. Each independent commuting generator splits the space into ±1 "
                "eigenspaces of equal size, halving the dimension, so the code space has "
                "dimension 2⁴/2² = 4 = 2², i.e. k = n − r = 4 − 2 = 2 logical qubits."
            ),
        ),
        Part(
            part_id="b",
            prompt=(
                "Exhibit logical operators X̄₁, Z̄₁, X̄₂, Z̄₂: Pauli strings that commute "
                "with S₁ and S₂, satisfy X̄ᵢZ̄ᵢ = −Z̄ᵢX̄ᵢ and [X̄ᵢ, Z̄ⱼ] = 0 for i ≠ j, "
                "and are not in S. Verify the required (anti)commutations."
            ),
            points=4,
            rubric=[
                "Presents a valid set, e.g. X̄₁ = X₁X₂, Z̄₁ = Z₁Z₃, X̄₂ = X₁X₃, "
                "Z̄₂ = Z₁Z₂ (any correct choice accepted — must check the relations for "
                "the choice actually made).",
                "Checks commutation with both stabilizer generators (even overlap "
                "counting: each proposed weight-2 X-string overlaps ZZZZ in 2 "
                "anticommuting places, etc.).",
                "Checks the symplectic pairing: X̄ᵢ anticommutes with Z̄ᵢ (odd overlap) "
                "and commutes with Z̄ⱼ, j ≠ i (even/zero overlap); notes the operators "
                "are not products of stabilizers (weight 2, while nontrivial stabilizer "
                "elements have weight 4).",
            ],
            model_solution=(
                "Take X̄₁ = X₁X₂, Z̄₁ = Z₁Z₃, X̄₂ = X₁X₃, Z̄₂ = Z₁Z₂ (all verified "
                "numerically):\n"
                "• vs S₁ = XXXX: the Z-type logicals overlap in 2 positions with "
                "anticommuting factors → (−1)² = +1: commute. X-type logicals share only "
                "X factors: commute.\n"
                "• vs S₂ = ZZZZ: X-type logicals overlap in 2 anticommuting positions: "
                "commute; Z-type share only Z factors: commute.\n"
                "• X̄₁ = X₁X₂ vs Z̄₁ = Z₁Z₃: single anticommuting overlap (qubit 1) → "
                "anticommute ✓. X̄₂ = X₁X₃ vs Z̄₂ = Z₁Z₂: overlap only on qubit 1 → "
                "anticommute ✓.\n"
                "• Cross pairs: X̄₁ vs Z̄₂ overlap on qubits 1,2 (two anticommutations) → "
                "commute ✓; X̄₂ vs Z̄₁ overlap on qubits 1,3 → commute ✓.\n"
                "All four have weight 2, whereas the nontrivial elements of S "
                "(S₁, S₂, S₁S₂ = YYYY up to phase) have weight 4, so none lies in S: "
                "they act nontrivially on the code space and generate the logical "
                "Pauli group."
            ),
        ),
        Part(
            part_id="c",
            prompt=(
                "Show the code has distance d = 2: (i) every weight-1 Pauli error "
                "anticommutes with at least one stabilizer generator (so all "
                "single-qubit errors are DETECTED), and (ii) there exists a weight-2 "
                "Pauli that commutes with S but acts nontrivially on the code space. "
                "Why does d = 2 mean the code can detect but not correct single-qubit "
                "errors?"
            ),
            points=3,
            rubric=[
                "(i) Case check: a single Xᵢ anticommutes with S₂ = ZZZZ; a single Zᵢ "
                "anticommutes with S₁ = XXXX; a single Yᵢ anticommutes with both — every "
                "weight-1 error flips at least one syndrome bit.",
                "(ii) Exhibits a weight-2 logical (e.g. X₁X₂ from part b) that commutes "
                "with all stabilizers but is not in S ⇒ an undetectable nontrivial "
                "error ⇒ d = 2 (minimum weight of N(S)∖S).",
                "Correction vs detection: correcting all weight-t errors needs "
                "d ≥ 2t+1 (distinct errors must have distinguishable syndromes / "
                "Knill–Laflamme); d = 2 only guarantees detection of weight-1 errors "
                "(2 = t+1 with t = 1), since two different single-qubit errors can "
                "produce the same syndrome and their product can be a logical.",
            ],
            model_solution=(
                "(i) Any Xᵢ shares exactly one anticommuting position with ZZZZ, so it "
                "anticommutes with S₂ and flips its syndrome; any Zᵢ likewise "
                "anticommutes with XXXX; Yᵢ ∝ XᵢZᵢ anticommutes with both. So every "
                "weight-1 error is detected (numerically: Z₁ anticommutes with XXXX, "
                "X₁ with ZZZZ).\n"
                "(ii) X̄₁ = X₁X₂ commutes with both generators yet is a logical operator "
                "(weight 2, not in S) — an undetectable error that corrupts the encoded "
                "information. Hence the minimum weight of an undetectable nontrivial "
                "error is 2: d = 2.\n"
                "A distance-d code detects up to d−1 errors but corrects only "
                "⌊(d−1)/2⌋. With d = 2: detection of any single error, correction of "
                "none — e.g. errors X₁ and X₂ have identical syndromes, and choosing the "
                "wrong recovery implements X₁X₂ = X̄₁, a logical fault. The [[4,2,2]] "
                "code is therefore used for error detection / post-selection, or as the "
                "base of concatenated and flag-qubit schemes."
            ),
        ),
    ],
)
