"""Curriculum data — mathematical foundations for quantum computing."""

TOPICS: dict[str, list[str]] = {
    "Linear Algebra": [
        "vector spaces, subspaces, span, and linear independence",
        "inner product spaces and Hilbert spaces",
        "orthonormal bases and the Gram-Schmidt process",
        "linear maps, kernels, images, and the rank-nullity theorem",
        "matrix representations of linear operators",
        "change of basis and similarity transformations",
        "eigenvalues, eigenvectors, and the characteristic polynomial",
        "diagonalisation and the spectral theorem for normal operators",
        "Hermitian operators: real eigenvalues and orthogonal eigenspaces",
        "unitary operators: norm preservation and eigenvalues on the unit circle",
        "tensor products of vector spaces and of operators",
        "trace, determinant, and their invariance properties",
        "singular value decomposition (SVD)",
        "density matrices and the space of positive semi-definite operators",
        "partial trace and reduced density matrices",
        "matrix exponentials and the connection to Lie algebras",
        "norms and operator norms",
        "the adjoint (†) of a linear operator",
        "projectors and projection-valued measures",
        "Schmidt decomposition of bipartite quantum states",
    ],
    "Abstract Algebra": [
        "groups: axioms, examples, and order",
        "subgroups, cosets, and Lagrange's theorem",
        "normal subgroups, quotient groups, and homomorphisms",
        "the isomorphism theorems",
        "cyclic groups and generators",
        "permutation groups and Cayley's theorem",
        "direct products and semi-direct products",
        "rings and ring homomorphisms",
        "ideals and quotient rings",
        "fields and field extensions",
        "finite fields GF(2) and GF(4) in quantum error correction",
        "the Pauli group as a finite group — structure and center",
        "the Clifford group and its role in quantum computing",
        "stabilizer subgroups and abelian subgroups of the Pauli group",
        "Lie groups: definition, examples, and the exponential map",
        "SU(2) and U(1) as Lie groups relevant to qubits",
        "Lie algebras: bracket operation, su(2), and generators",
        "the symplectic group Sp(2n) and symplectic structure of Pauli group",
    ],
    "Representation Theory": [
        "group representations: definition and homomorphism property",
        "subrepresentations and irreducible representations",
        "Maschke's theorem and complete reducibility",
        "Schur's lemma and its consequences",
        "characters of representations and orthogonality relations",
        "character tables and their properties",
        "representations of cyclic groups and Fourier analysis connection",
        "representations of SU(2) and spin-j states",
        "Clebsch-Gordan decomposition and addition of angular momenta",
        "the adjoint representation of a Lie algebra",
        "tensor product representations",
        "induced and restricted representations",
        "the hidden subgroup problem and its representation-theoretic formulation",
        "quantum Fourier transform as a character sum over abelian groups",
        "Peter-Weyl theorem for compact groups",
    ],
    "Complex Analysis": [
        "complex numbers: polar form, argument, and modulus",
        "holomorphic functions and the Cauchy-Riemann equations",
        "complex power series and radius of convergence",
        "the exponential function and Euler's formula e^{iθ} = cos θ + i sin θ",
        "contour integrals and path independence",
        "Cauchy's integral theorem and Cauchy's integral formula",
        "Laurent series and classification of isolated singularities",
        "the residue theorem and applications to real integrals",
        "analytic continuation",
        "branch cuts and multi-valued functions (√z, log z)",
        "conformal mappings and Möbius transformations",
        "the argument principle and Rouché's theorem",
        "entire functions and Liouville's theorem",
        "the Schwarz lemma",
        "connection between complex exponentials and quantum phases",
    ],
    "Calculus & Real Analysis": [
        "ε-δ definitions of limits and continuity",
        "differentiation rules and the chain rule",
        "Taylor and Maclaurin series",
        "integration: Riemann vs Lebesgue perspectives",
        "the fundamental theorem of calculus",
        "uniform convergence and interchange of limits",
        "multivariable calculus: partial derivatives and gradients",
        "the chain rule for multivariable functions",
        "Lagrange multipliers for constrained optimisation",
        "metric spaces, open/closed sets, and compactness",
        "sequences and series of functions",
        "differentiation under the integral sign",
        "vector calculus: divergence, curl, and Stokes' theorem",
        "variational calculus and the Euler-Lagrange equation",
        "matrix calculus: gradient of a scalar with respect to a matrix",
        "convex functions, convex sets, and the supporting hyperplane theorem",
        "semidefinite programming and convex optimisation in quantum information",
    ],
    "Ordinary Differential Equations": [
        "first-order ODEs: separable, linear, and exact equations",
        "linear second-order ODEs with constant coefficients",
        "the Wronskian and linear independence of solutions",
        "power series solutions and Frobenius method",
        "the Schrödinger equation as a linear ODE",
        "systems of first-order ODEs and matrix exponentials",
        "eigenvalue method for constant-coefficient systems",
        "phase portraits and qualitative analysis",
        "the Hamiltonian formalism and Hamilton's equations",
        "Liouville's theorem for Hamiltonian systems",
        "perturbation theory for ODEs",
    ],
    "Partial Differential Equations": [
        "classification: elliptic, parabolic, and hyperbolic PDEs",
        "the heat equation and diffusion",
        "the wave equation and separation of variables",
        "the time-dependent Schrödinger equation",
        "the time-independent Schrödinger equation as an eigenvalue PDE",
        "Sturm-Liouville theory and orthogonal function expansions",
        "Fourier series solutions to boundary value problems",
        "Green's functions",
        "the Dirac delta and distributional solutions",
        "the Laplace equation and harmonic functions",
        "the Wigner function: phase-space quasi-probability distribution",
        "continuous-variable quantum computing and Gaussian states",
        "the Lindblad equation as a PDE for the density matrix",
    ],
    "Functional Analysis": [
        "normed spaces and Banach spaces",
        "Hilbert spaces: definition, orthonormal bases, and Parseval's identity",
        "bounded linear operators and the operator norm",
        "the Riesz representation theorem",
        "compact operators and their spectral theory",
        "self-adjoint operators and their spectral decomposition",
        "the spectral theorem for unbounded self-adjoint operators",
        "closed and closable operators",
        "the resolvent and spectrum of an operator",
        "Stone's theorem: one-parameter unitary groups",
        "the tensor product of Hilbert spaces",
        "trace-class and Hilbert-Schmidt operators",
        "quantum states as density operators on a Hilbert space",
        "positive operator-valued measures (POVMs)",
        "completely positive maps and quantum channels",
    ],
    "Probability Theory": [
        "probability spaces, σ-algebras, and measures",
        "random variables and their distributions",
        "expectation, variance, and higher moments",
        "conditional probability and Bayes' theorem",
        "the law of large numbers",
        "the central limit theorem",
        "Markov chains and stationary distributions",
        "entropy: Shannon entropy and its properties",
        "mutual information and channel capacity",
        "quantum probability and the Born rule",
        "quantum entropy: von Neumann entropy",
        "quantum mutual information and entanglement measures",
        "the Holevo bound and accessible information",
        "random matrix theory and the Wigner semicircle law",
    ],
    "Fourier Analysis": [
        "Fourier series: coefficients, convergence, and Parseval's theorem",
        "the Fourier transform on ℝ and its properties",
        "convolution theorem and the relationship to multiplication",
        "the Dirac delta as a distribution and its Fourier transform",
        "the discrete Fourier transform (DFT)",
        "the fast Fourier transform (FFT) algorithm",
        "the quantum Fourier transform (QFT) as a DFT on amplitudes",
        "Fourier analysis on finite abelian groups",
        "characters of abelian groups as Fourier basis functions",
        "Pontryagin duality",
        "Heisenberg uncertainty principle as a Fourier uncertainty relation",
        "the short-time Fourier transform and wavelet transforms",
        "applications of Fourier analysis in quantum phase estimation",
    ],
    "Number Theory": [
        "divisibility, primes, and the fundamental theorem of arithmetic",
        "the Euclidean algorithm and Bézout's identity",
        "modular arithmetic and congruences",
        "Euler's totient function φ(n) and Euler's theorem",
        "Fermat's little theorem and applications",
        "the Chinese remainder theorem",
        "quadratic residues and the Legendre symbol",
        "the order of an element in Z/nZ",
        "primitive roots and discrete logarithms",
        "integer factorisation and the RSA problem",
        "the period-finding problem and its reduction to factoring",
        "continued fractions and rational approximation",
        "lattices and lattice-based cryptography basics",
        "elliptic curves over finite fields",
    ],
    "Topology & Geometry": [
        "topological spaces: open sets, continuity, and homeomorphisms",
        "compactness and the Heine-Borel theorem",
        "connectedness and path-connectedness",
        "the fundamental group π₁ and covering spaces",
        "homotopy and homotopy equivalence",
        "manifolds: definition, charts, and examples",
        "smooth manifolds and tangent spaces",
        "fibre bundles and the geometric phase (Berry phase)",
        "the Bloch sphere as a 2-sphere S² and qubit geometry",
        "differential forms and de Rham cohomology",
        "Lie groups as smooth manifolds",
        "topological phases of matter and the toric code",
        "anyons and non-abelian statistics in topological QC",
        "knot theory and topological quantum computation",
        "Chern numbers and topological invariants",
    ],
    "Quantum Connections": [
        "Fourier analysis on ℤ/Nℤ and the period-finding step in Shor's algorithm",
        "group representations and the hidden subgroup problem framework",
        "tensor product Hilbert spaces and the Schmidt decomposition of entangled states",
        "completely positive maps: Kraus operators linking functional analysis to quantum channels",
        "von Neumann entropy from probability theory to the Holevo bound",
        "Trotter-Suzuki decomposition: ODE approximation theory applied to Hamiltonian simulation",
        "Berry phase and holonomy: differential geometry in adiabatic quantum computing",
        "stabiliser codes: linear algebra over GF(2) and the stabiliser formalism",
        "the quantum Fourier transform as a unitary from representation theory",
        "semidefinite programming and entanglement witnesses in quantum information",
        "random matrix theory and level statistics in quantum chaos",
        "Lie group exponentials and the synthesis of arbitrary single-qubit gates",
        "knot invariants, anyon models, and topological quantum computation",
        "the Wigner function bridging classical probability and quantum phase space",
        "spectral graph theory and the analysis of quantum walk algorithms",
        "convex geometry of the set of quantum states (density matrices)",
        "continued fractions, the quantum phase estimation algorithm, and Diophantine approximation",
    ],
}

DIFFICULTY_LEVELS: list[str] = ["beginner", "intermediate", "advanced", "expert"]

QUESTION_TYPES: list[str] = [
    "conceptual explanation",
    "proof sketch",
    "calculation",
    "example construction",
    "compare and contrast",
    "counterexample",
]
