"""Prefilled GitHub issue URLs for reporting a wrong or ambiguous study item.

The repository is public.  When a card is wrong or an exam question is
ambiguous there is currently no path from "this is wrong" to a fix except
remembering it later — and nobody remembers it later.  This module turns one
click inside an app into a GitHub issue that is already filled in: the file,
the item id, the text as the learner saw it, and their comment.

Pure and offline.  It builds a URL string; nothing here opens a browser or
touches the network, so it is trivially testable and cannot stall a drill.
``common.ui.errata_dialog`` is the Qt side that collects the comment and hands
the URL to ``QDesktopServices``.

The URL targets the repository's **Content error** issue form
(``.github/ISSUE_TEMPLATE/content_error.yml``), whose field ids this module
mirrors: ``file``, ``quote``, ``why_wrong``, ``correction``, ``evidence``,
``severity``.  GitHub prefills a form by matching ``?<field-id>=<value>`` query
parameters, so the report lands in the right boxes instead of as one blob of
prose.  A template that is missing (or an ``id`` that is renamed) degrades to
an ordinary prefilled issue body — the report still arrives.
"""
from __future__ import annotations

from urllib.parse import quote, urlencode

#: The repository issues live in.
REPO = "matthewscottconroy/quantum-computing-study-suite"

#: Issue form used for "this study item is wrong".
TEMPLATE = "content_error.yml"

#: Labels applied by the form itself; repeated here so a plain-body fallback
#: (no template) still lands in the same triage bucket.
LABELS: tuple[str, ...] = ("content",)

#: Severity options, exactly as the dropdown in content_error.yml lists them.
SEVERITIES: dict[str, str] = {
    "wrong": "Wrong — teaches something false, or a bank answer is incorrect",
    "misleading": "Misleading — technically defensible but reads wrong",
    "typo": "Typo or formatting only",
}
DEFAULT_SEVERITY = "wrong"

#: Where each app's items live, for the "File" field.  A report that names the
#: file is close to a patch; one that says "the quiz was wrong" is not.
APP_ITEM_PATHS: dict[str, str] = {
    "circuit-trainer": "circuit-trainer/problems/",
    "exam-sim":        "exam-sim/bank/",
    "flashcard-drill": "flashcard-drill/cards/",
    "math-quiz":       "math-quiz/ (generated by Claude — quote the question)",
    "paper-drill":     "paper-drill/ (generated from your paper — quote the question)",
    "problem-trainer": "problem-trainer/problems/",
    "qec-trainer":     "qec-trainer/problems/",
    "qiskit-dojo":     "qiskit-dojo/katas/",
    "quantum-quiz":    "quantum-quiz/ (generated by Claude — quote the question)",
    "vqa-trainer":     "vqa-trainer/problems/",
}

#: Hard cap on the whole URL.  GitHub accepts long query strings but browsers
#: and mail clients vary; 6000 is comfortably inside every limit that matters.
#: Fields are truncated longest-first so the short, high-signal ones (file,
#: item id) always survive.
MAX_URL = 6000

_TRUNCATED = "\n\n[truncated — see the app for the full text]"


def issue_base_url(repo: str = REPO) -> str:
    """The ``/issues/new`` endpoint for *repo*."""
    return f"https://github.com/{repo}/issues/new"


def item_location(app: str, item_id: str = "") -> str:
    """The "File" field value for an item: its directory, plus the id.

    Bank items are one file per item whose stem *is* the id, so naming both
    gives the exact path.  Generated items (math-quiz, quantum-quiz,
    paper-drill) have no file; the quoted text is the only handle, and the
    string says so.
    """
    base = APP_ITEM_PATHS.get(app, f"{app}/")
    ident = str(item_id).strip()
    if not ident:
        return base
    if base.endswith("/"):
        return f"{base} — item id `{ident}`"
    return f"{base} — item id `{ident}`"


def issue_title(app: str, item_id: str = "", *, prefix: str = "[content] ") -> str:
    """The issue title: the template's own prefix, the app, and the item."""
    ident = str(item_id).strip()
    tail = f"{app}: {ident}" if ident else app
    return f"{prefix}{tail}"


def _truncate_to_fit(url_for, fields: dict[str, str], limit: int) -> dict[str, str]:
    """Shrink the longest field repeatedly until ``url_for(fields)`` fits."""
    fields = dict(fields)
    while len(url_for(fields)) > limit:
        key = max(fields, key=lambda k: len(fields[k]))
        value = fields[key]
        if len(value) <= len(_TRUNCATED) + 40:
            # Nothing left worth cutting in the biggest field: drop it and stop
            # shrinking if that did not help either.
            if len(fields) <= 1:
                fields[key] = value[: max(0, limit // 2)]
                return fields
            del fields[key]
            continue
        keep = max(40, len(value) - max(80, len(value) // 4))
        fields[key] = value[:keep].rstrip() + _TRUNCATED
    return fields


def issue_url(app: str, item_id: str = "", item_text: str = "",
              comment: str = "", *, severity: str = DEFAULT_SEVERITY,
              correction: str = "", repo: str = REPO,
              template: str | None = TEMPLATE, max_url: int = MAX_URL) -> str:
    """A GitHub "new issue" URL, prefilled for one wrong study item.

    ``app``        the app directory name the item was shown in.
    ``item_id``    the item's id (a bank file stem, a card id, a kata id).
    ``item_text``  the item as the learner saw it — the "quote it exactly"
                   field.  This is the part a maintainer cannot reconstruct.
    ``comment``    what the learner says is wrong: the "Why it is wrong" field.
    ``severity``   one of :data:`SEVERITIES` (``"wrong"``, ``"misleading"``,
                   ``"typo"``); anything else falls back to the default.
    ``correction`` the fix, when they have one.
    ``template``   None builds a plain ``?title=&body=`` issue instead of a
                   form prefill — use it for a repo without the issue form.

    Returns a URL string.  Opens nothing, sends nothing.
    """
    ident = str(item_id).strip()
    title = issue_title(app, ident)
    fields: dict[str, str] = {}
    structural: tuple[str, ...]

    if template:
        # Structural fields, in the order GitHub should see them.  These are
        # never trimmed: a report with no title and no form is not a report.
        structural = ("template", "title", "severity")
        fields["template"] = template
        fields["title"] = title
        fields["severity"] = SEVERITIES.get(severity, SEVERITIES[DEFAULT_SEVERITY])
        fields["file"] = item_location(app, ident)
        fields["quote"] = str(item_text or "").strip()
        fields["why_wrong"] = str(comment or "").strip()
        fields["correction"] = correction.strip()
    else:
        structural = ("title", "labels")
        fields["title"] = title
        if LABELS:
            fields["labels"] = ",".join(LABELS)
        fields["body"] = issue_body(app, ident, item_text, comment,
                                    severity=severity, correction=correction)
    fields = {k: v for k, v in fields.items() if v}

    fixed: dict[str, str] = {k: fields[k] for k in structural if k in fields}
    variable: dict[str, str] = {k: v for k, v in fields.items()
                                if k not in fixed}

    def build(rest: dict[str, str]) -> str:
        merged: dict[str, str] = {**fixed, **rest}
        return f"{issue_base_url(repo)}?{urlencode(merged, quote_via=quote)}"

    return build(_truncate_to_fit(build, variable, max_url))


def issue_body(app: str, item_id: str = "", item_text: str = "",
               comment: str = "", *, severity: str = DEFAULT_SEVERITY,
               correction: str = "") -> str:
    """The Markdown body used when no issue form is available.

    Also handy on its own: an app can show it in a "copy this" box for someone
    who would rather not open a browser from inside a study session.
    """
    parts = [
        "**File**",
        "",
        item_location(app, item_id),
        "",
        "**Quote the text exactly as it appears**",
        "",
        "```text",
        str(item_text or "").strip() or "(not captured)",
        "```",
        "",
        "**Why it is wrong**",
        "",
        str(comment or "").strip() or "(not given)",
    ]
    if correction.strip():
        parts += ["", "**What it should say**", "", correction.strip()]
    parts += [
        "",
        "**Severity**",
        "",
        SEVERITIES.get(severity, SEVERITIES[DEFAULT_SEVERITY]),
        "",
        f"*Reported from {app} via the in-app errata button.*",
    ]
    return "\n".join(parts)


__all__ = [
    "REPO", "TEMPLATE", "LABELS", "SEVERITIES", "DEFAULT_SEVERITY",
    "APP_ITEM_PATHS", "MAX_URL",
    "issue_base_url", "item_location", "issue_title", "issue_url", "issue_body",
]
