"""Curriculum data — single source of truth for all subjects and topics."""

TOPICS: dict[str, list[str]] = {
    "Linear Algebra": [
        "vector spaces and the Dirac bra-ket notation",
        "inner product spaces and Hilbert spaces",
        "tensor products of vector spaces",
        "Hermitian and unitary matrices",
        "eigenvalues, eigenvectors, and the spectral theorem",
        "spectral decomposition of quantum observables",
        "density matrices and mixed states",
        "partial trace and reduced density matrices",
        "matrix exponentials and gate construction from generators",
    ],
    "Abstract Algebra": [
        "group axioms and examples in quantum computing",
        "Lie groups and Lie algebras — SU(2) and U(1)",
        "the exponential map from Lie algebra to Lie group",
        "finite fields GF(2) and GF(4) in error correction",
        "the symplectic structure of the Pauli group",
        "the Clifford algebra and Pauli matrices",
        "the Gottesman-Knill theorem",
    ],
    "Representation Theory": [
        "irreducible representations and Maschke's theorem",
        "Schur's lemma and character tables",
        "representations of SU(2) and spin-j states",
        "Clebsch-Gordan decomposition",
        "the Pauli group structure and its center",
        "stabilizer subgroups as abelian representations",
        "the quantum Fourier transform as a character sum",
        "the hidden subgroup problem",
    ],
    "Quantum Mechanics": [
        "the four postulates of quantum mechanics",
        "the Bloch sphere representation of a qubit",
        "projective measurements and the Born rule",
        "commutators and the uncertainty principle",
        "POVMs — positive operator-valued measures",
        "the Schrödinger equation and time evolution",
        "entanglement and the Schmidt decomposition",
        "Bell states and entanglement entropy",
        "open quantum systems and the Lindblad master equation",
        "Kraus operators and quantum channels",
        "T1 and T2 decoherence times",
    ],
    "Quantum Computing": [
        "the quantum circuit model — qubits, gates, measurement",
        "single-qubit gates: X, Y, Z, H, S, T, Rx, Ry, Rz",
        "two-qubit gates: CNOT, CZ, SWAP, Toffoli",
        "universality and the Solovay-Kitaev theorem",
        "the Clifford + T gate set",
        "ZYZ decomposition of single-qubit unitaries",
        "quantum complexity classes: BQP, QMA, PSPACE",
        "the no-cloning theorem",
        "quantum error correcting codes — 3-qubit bit-flip and phase-flip",
        "Shor's 9-qubit code",
        "the stabilizer formalism and syndrome measurement",
        "CSS codes — Calderbank-Shor-Steane construction",
        "fault tolerance thresholds",
        "transversal gates",
        "magic state distillation",
        "the surface code",
    ],
    "Qiskit": [
        "building circuits with QuantumCircuit",
        "the Qiskit gate library — all standard gates",
        "AerSimulator methods: statevector, qasm, density_matrix",
        "adding noise models with NoiseModel and depolarizing_error",
        "Statevector and DensityMatrix in qiskit.quantum_info",
        "SparsePauliOp for Hamiltonian representation",
        "parameterized circuits with Parameter and ParameterVector",
        "the hardware-efficient ansatz",
        "SamplerV2 and EstimatorV2 primitives",
        "submitting jobs to IBM Quantum hardware",
        "zero-noise extrapolation error mitigation",
    ],
    "QASM": [
        "OpenQASM 2 file structure and syntax",
        "standard gates in qelib1.inc",
        "defining custom gates in QASM 2",
        "OpenQASM 3 classical types and control flow",
        "mid-circuit measurement and feed-forward in QASM 3",
        "defcal and pulse-level gate definitions in QASM 3",
        "QASM as an interchange format between quantum SDKs",
        "importing and exporting QASM in Qiskit",
    ],
    "Foundations of Quantum Mechanics": [
        "the quantum measurement problem",
        "the Copenhagen interpretation",
        "the Many-Worlds (Everett) interpretation",
        "pilot wave / de Broglie-Bohm theory",
        "the EPR argument and local hidden variables",
        "Bell's theorem and the CHSH inequality",
        "the Tsirelson bound",
        "loophole-free Bell tests",
        "decoherence and einselection",
        "pointer states and the quantum-to-classical transition",
        "the no-cloning and no-deleting theorems",
        "the Holevo bound and superdense coding",
        "quantum teleportation",
        "Hardy's axioms for reconstructing quantum mechanics",
    ],
    "Quantum Algorithm Design": [
        "phase kickback technique",
        "quantum parallelism and constructive interference",
        "quantum phase estimation (QPE)",
        "amplitude amplification — generalized Grover",
        "the quantum Fourier transform circuit",
        "the Deutsch-Jozsa algorithm",
        "Shor's algorithm — structure and complexity",
        "Grover's algorithm — iteration count and optimality",
        "the HHL algorithm for linear systems",
        "VQE — variational quantum eigensolver",
        "QAOA — quantum approximate optimization algorithm",
        "Hamiltonian simulation via Trotter decomposition",
        "qubitization and LCU methods",
        "quantum query complexity and lower bounds",
        "the BBBV theorem and Grover optimality",
        "the hidden subgroup problem",
    ],
    "Transpiling": [
        "the quantum transpilation pipeline overview",
        "basis translation and single-qubit gate decomposition",
        "the ZYZ and KAK two-qubit decompositions",
        "qubit routing and the SWAP insertion problem",
        "the SABRE routing algorithm",
        "layout strategies: trivial, dense, SABRE, VF2",
        "circuit optimization passes — cancellation and merging",
        "Clifford optimization and peephole optimization",
        "the Qiskit PassManager and pass types",
        "writing a custom TransformationPass",
        "noise-aware layout and error-weighted routing",
        "transpilation optimization levels 0–3",
        "dynamic circuits and feed-forward after mid-circuit measurement",
        "circuit metrics: depth, CX count, T count, expected fidelity",
    ],
    "Qiskit Certification (C1000-179)": [
        "constructing SamplerV2 PUBs — (circuit, parameter_values, shots) tuples",
        "reading Sampler results: result[0].data.<creg>.get_counts()",
        "constructing EstimatorV2 PUBs — circuits, observables, parameter values, precision",
        "reading Estimator results: data.evs and data.stds",
        "generate_preset_pass_manager and the ISA circuit requirement",
        "execution modes: job, Session, and Batch",
        "selecting the right visualization function — plot_histogram vs plot_distribution vs Bloch/qsphere/city plots",
        "little-endian qubit ordering in labels, counts keys, and statevectors",
        "OpenQASM 2 and 3 syntax and Qiskit dumps/loads round-tripping",
        "quantum_info operators: Operator, SparsePauliOp, Statevector methods",
    ],
}

DIFFICULTY_LEVELS: list[str] = ["beginner", "intermediate", "advanced", "expert"]

QUESTION_TYPES: list[str] = [
    "conceptual explanation",
    "mathematical derivation",
    "compare and contrast",
    "circuit design",
    "error analysis",
    "proof sketch",
    "teach-back",
]

# Maps each subject to which Qiskit context mode to use.
# "circuit"      → build a QuantumCircuit and render it
# "hamiltonian"  → build a SparsePauliOp and format Pauli terms
# "statevector"  → build a Statevector and show amplitude table
# None           → no Qiskit context (conceptual-only topics)
SUBJECT_CONTEXT_MODE: dict[str, str | None] = {
    "Linear Algebra":                   "hamiltonian",
    "Abstract Algebra":                 "hamiltonian",
    "Representation Theory":            "hamiltonian",
    "Quantum Mechanics":                "statevector",
    "Quantum Computing":                "circuit",
    "Qiskit":                           "circuit",
    "QASM":                             "circuit",
    "Foundations of Quantum Mechanics": "statevector",
    "Quantum Algorithm Design":         "circuit",
    "Transpiling":                      "circuit",
    "Qiskit Certification (C1000-179)": "circuit",
}
