"""Problem: stab_clifford"""
from __future__ import annotations
from core.models import Problem, GradeMode

PROBLEM = Problem(
    id='stab_clifford',
    category='Stabilizer Formalism',
    difficulty='advanced',
    question='The Clifford group is defined as the set of unitaries that:',
    choices=[
        'Map the Pauli group to itself under conjugation',
        'Commute with all Pauli operators',
        'Are generated by T and CNOT alone',
        'Preserve the computational basis',
    ],
    correct_index=0,
    explanation='U is Clifford iff UPU† ∈ Pₙ for every Pauli P ∈ Pₙ. This means Clifford unitaries map Pauli operators to Pauli operators. By Gottesman-Knill, Clifford circuits are classically simulable.',
    hints=[
        'Clifford circuits map stabilizer states to stabilizer states.',
    ],
    grade_mode=GradeMode.AUTO,
)
