"""Problem: stab_plus_state_stabilizers"""
from __future__ import annotations
from core.models import Problem, GradeMode

PROBLEM = Problem(
    id='stab_plus_state_stabilizers',
    category='Stabilizer Formalism',
    difficulty='beginner',
    question='The n-qubit all-plus state |+⟩^⊗n is stabilized by which generators?',
    choices=[
        'Xᵢ for each qubit i = 1, …, n (one X per qubit)',
        'Zᵢ for each qubit i',
        'X₁X₂⋯Xₙ (only the product, one generator)',
        'H⊗ⁿ applied to Z stabilizers',
    ],
    correct_index=0,
    explanation='Each |+⟩ qubit is individually stabilized by X (since X|+⟩ = |+⟩). For the product state |+⟩^⊗n, the stabilizer group is generated by {X₁, X₂, …, Xₙ} — one X per qubit, each acting independently. This is an n-dimensional stabilizer group fixing the unique stabilizer state |+⟩^⊗n. Graph states on graphs with no edges are exactly |+⟩^⊗n.',
    hints=[
        'Each |+⟩ = (|0⟩+|1⟩)/√2 is the +1 eigenstate of X.',
    ],
    grade_mode=GradeMode.AUTO,
)
