"""Problem: stab_ghz_generators_explicit"""
from __future__ import annotations
from core.models import Problem, GradeMode

PROBLEM = Problem(
    id='stab_ghz_generators_explicit',
    category='Stabilizer Formalism',
    difficulty='beginner',
    question='The 3-qubit GHZ state has stabilizer generators XXX, ZZI, IZZ. Which of the following is also in the stabilizer group (but not a generator)?',
    choices=[
        'ZIZ — the product of ZZI and IZZ',
        'XXZ — not derivable from the generators',
        'YYY — not stabilizer of GHZ',
        'ZZZ — anticommutes with XXX',
    ],
    correct_index=0,
    explanation='The stabilizer group is generated by {XXX, ZZI, IZZ} and is closed under multiplication. ZZI · IZZ = Z(Z·I)(I·Z) = ZIZ (using Z·I=Z and I·Z=Z on middle qubit: Z·Z=I, wait — on qubit 1: Z·I=Z; qubit 2: Z·Z=I; qubit 3: I·Z=Z → ZIZ). ZIZ is a valid stabilizer: ZIZ|GHZ⟩ = Z|0⟩⊗I|0⟩⊗Z|0⟩+Z|1⟩⊗I|1⟩⊗Z|1⟩ = |0⟩|0⟩|0⟩+(-1)(-1)|1⟩|1⟩|1⟩ = |GHZ⟩ ✓.',
    hints=[
        'Multiply pairs of generators to get new group elements.',
    ],
    grade_mode=GradeMode.AUTO,
)
