"""Card: cz_07_05_layer_fidelity_eplg_d3745679

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_layer_fidelity_eplg_d3745679',
    category='Cloze',
    front='Layer fidelity / EPLG:  LF = ______',
    back='LF = Π Fᵢ  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
