"""Card: cz_04_01_phase_oracle_from_bit_oracle_cd4e3f23

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_01_phase_oracle_from_bit_oracle_cd4e3f23',
    category='Cloze',
    front='Phase oracle from bit oracle:  O_f|x⟩|-⟩ = ______',
    back='O_f|x⟩|-⟩ = (-1)^{f(x)}|x⟩|-⟩  ·  Source: docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — Quantum Parallelism and Interference',
)
