"""Card: cz_07_04_interleaved_rb_gate_error_a192140a

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/04_benchmarking_and_characterization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_04_interleaved_rb_gate_error_a192140a',
    category='Cloze',
    front='Interleaved RB gate error:  r_G ≈ ______',
    back='r_G ≈ (1 - p_int/p_ref) (2^n-1)/2^n  ·  Source: docs/07_quantum_hardware/04_benchmarking_and_characterization.md — Benchmarking and Characterization of Quantum Hardware',
)
