"""Card: cz_02_05_density_matrix_of_pure_state_adcd1612

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_05_density_matrix_of_pure_state_adcd1612',
    category='Cloze',
    front='Density matrix of pure state:  ρ = ______',
    back='ρ = |ψ⟩⟨ψ|  ·  Full entry: ρ = |ψ⟩⟨ψ|,  Tr(ρ^2) = 1  ·  Source: docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — Density Matrices and Open Systems',
)
