"""Card: cz_04_01_hadamard_transform_on_basis_6d76d971

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_01_hadamard_transform_on_basis_6d76d971',
    category='Cloze',
    front='Hadamard transform on basis state:  H^{⊗n}|x⟩ = ______',
    back='H^{⊗n}|x⟩ = 1/√(2^n) Σ_y(-1)^{x·y}|y⟩  ·  Source: docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — Quantum Parallelism and Interference',
)
