"""Card: cz_04_05_grover_operator_6c2eeb10

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/05_grover_search.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_05_grover_operator_6c2eeb10',
    category='Cloze',
    front='Grover operator:  G = ______',
    back="G = (2|s⟩⟨s| - I)(I - 2|x^*⟩⟨x^*|)  ·  Source: docs/04_quantum_algorithms/05_grover_search.md — Grover's Search Algorithm",
)
