"""Card: cz_02_07_quadratures_bc06c0ec

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_quadratures_bc06c0ec',
    category='Cloze',
    front='Quadratures:  x̂ = ______',
    back='x̂ = √(ℏ/2mω)(â+â†)  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
