"""Card: cz_02_08_addition_7cb9715a

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_addition_7cb9715a',
    category='Cloze',
    front='Addition:  M = ______',
    back='M = m₁+m₂  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
