"""Card: cz_08_04_fibonacci_fusion_fef01cda

Generated by tools/gen_cloze.py from docs/08_advanced_topics/04_topological_quantum_computation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_04_fibonacci_fusion_fef01cda',
    category='Cloze',
    front='Fibonacci fusion:  τ × τ = ______',
    back='τ × τ = 1 + τ  ·  Source: docs/08_advanced_topics/04_topological_quantum_computation.md — Topological Quantum Computation',
)
