"""Card: cz_02_05_validity_conditions_66967ab9

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_05_validity_conditions_66967ab9',
    category='Cloze',
    front='Validity conditions:  ρ ≥ ______',
    back='ρ ≥ 0  ·  Full entry: ρ† = ρ,  ρ ≥ 0,  Tr(ρ) = 1  ·  Source: docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — Density Matrices and Open Systems',
)
