"""Card: cz_02_09_rwa_hamiltonian_0bb4e048

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/09_perturbation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_09_rwa_hamiltonian_0bb4e048',
    category='Cloze',
    front='RWA Hamiltonian:  Ĥ = ______',
    back='Ĥ = (ℏΔ/2)Z + (ℏΩ/2)X  ·  Source: docs/02_quantum_mechanics/09_perturbation_theory.md — Perturbation Theory and Driven Systems',
)
