"""Card: cz_01_01_pauli_algebra_eea27108

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/01_linear_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_01_pauli_algebra_eea27108',
    category='Cloze',
    front='Pauli algebra:  σ_i σ_j = ______',
    back='σ_i σ_j = δ_{ij} I + iε_{ijk}σ_k  ·  Source: docs/01_mathematical_foundations/01_linear_algebra.md — Linear Algebra for Quantum Computing',
)
