"""Card: cz_03_05_graph_state_7cb21f9f

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/05_measurement_based_qc.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_05_graph_state_7cb21f9f',
    category='Cloze',
    front='Graph state:  |G⟩ = ______',
    back='|G⟩ = ∏_{(u,v)∈ E} CZ_{uv}|+⟩^{⊗n}  ·  Full entry: |G⟩ = ∏_{(u,v)∈ E} CZ_{uv}|+⟩^{⊗n},  K_v = X_v ∏_{u∈ N(v)} Z_u,  K_v|G⟩ = |G⟩  ·  Source: docs/03_quantum_gates_and_circuits/05_measurement_based_qc.md — Measurement-Based Quantum Computation',
)
