"""Card: cz_02_02_density_matrix_from_bloch_ve_1b0fdb23

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_02_density_matrix_from_bloch_ve_1b0fdb23',
    category='Cloze',
    front='Density matrix from Bloch vector:  ρ = ______',
    back='ρ = (I + r·σ)/2  ·  Source: docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — Qubits and the Bloch Sphere',
)
