"""Card: cz_02_10_trace_distance_7da7ea56

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_trace_distance_7da7ea56',
    category='Cloze',
    front='Trace distance:  D(ρ,σ) = ______',
    back='D(ρ,σ) = ½‖ρ−σ‖₁  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
