"""Card: cz_06_07_mandelstam_tamm_qsl_4ca5260d

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_07_mandelstam_tamm_qsl_4ca5260d',
    category='Cloze',
    front='Mandelstam-Tamm QSL:  τ ≥ ______',
    back='τ ≥ πℏ / (2ΔE)  ·  Source: docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — Quantum Optimal Control',
)
