"""Card: cz_02_02_euler_decomposition_39daeac8

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_02_euler_decomposition_39daeac8',
    category='Cloze',
    front='Euler decomposition:  U = ______',
    back='U = e^{iγ}R_z(α)R_y(β)R_z(δ)  ·  Source: docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — Qubits and the Bloch Sphere',
)
