"""Card: cz_02_08_ladders_d253f2e8

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_ladders_d253f2e8',
    category='Cloze',
    front='Ladders:  Ĵ±|j,m⟩ = ______',
    back='Ĵ±|j,m⟩ = ℏ√(j(j+1) − m(m±1))|j,m±1⟩  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
