"""Card: cz_08_01_qma_completeness_5e917a6b

Generated by tools/gen_cloze.py from docs/08_advanced_topics/01_quantum_complexity_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_01_qma_completeness_5e917a6b',
    category='Cloze',
    front='QMA-completeness:  k ≥ ______',
    back='k ≥ 2  ·  Source: docs/08_advanced_topics/01_quantum_complexity_theory.md — Quantum Complexity Theory',
)
