"""Card: cz_02_10_contractivity_f5e47efd

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_contractivity_f5e47efd',
    category='Cloze',
    front='Contractivity:  D(ε(ρ), ε(σ)) ≤ ______',
    back='D(ε(ρ), ε(σ)) ≤ D(ρ,σ)  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
