"""Card: cz_06_05_noise_induced_plateau_c413e173

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/05_barren_plateaus.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_05_noise_induced_plateau_c413e173',
    category='Cloze',
    front='Noise-induced plateau:  |C(θ) - C_mix| ≤ ______',
    back='|C(θ) - C_mix| ≤ (1-p)^D ||O||  ·  Source: docs/06_variational_quantum_algorithms/05_barren_plateaus.md — Barren Plateaus',
)
