"""Card: cz_08_05_qsp_theorem_2d489543

Generated by tools/gen_cloze.py from docs/08_advanced_topics/05_qsvt.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_05_qsp_theorem_2d489543',
    category='Cloze',
    front='QSP theorem:  ⟨0|U_φ|0⟩ = ______',
    back='⟨0|U_φ|0⟩ = P(x)  ·  Source: docs/08_advanced_topics/05_qsvt.md — Quantum Singular Value Transformation',
)
