"""Card: cz_07_02_ms_effective_hamiltonian_87d9414e

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/02_trapped_ion_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_02_ms_effective_hamiltonian_87d9414e',
    category='Cloze',
    front='MS effective Hamiltonian:  H_eff = ______',
    back='H_eff = (Ω²η²/δ) (σₓ⊗σₓ)  ·  Source: docs/07_quantum_hardware/02_trapped_ion_qubits.md — Trapped Ion Qubits',
)
