"""Card: cz_05_02_dual_code_06bdad24

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/02_classical_error_correction.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_02_dual_code_06bdad24',
    category='Cloze',
    front='Dual code:  C⊥ = ______',
    back='C⊥ = {v : ⟨u,v⟩ = 0 ∀ u ∈ C}  ·  Source: docs/05_quantum_error_correction/02_classical_error_correction.md — Classical Error Correction',
)
