"""Card: cz_06_06_fundamental_sampling_lower_b_0ef30bb5

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_06_fundamental_sampling_lower_b_0ef30bb5',
    category='Cloze',
    front='Fundamental sampling lower bound (Takagi):  S_min ≥ ______',
    back='S_min ≥ e^{Ω(T·ε)}  ·  Source: docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — Noise and Error Mitigation in NISQ Algorithms',
)
