"""Card: cz_07_04_ramsey_fringe_d38b31e6

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/04_benchmarking_and_characterization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_04_ramsey_fringe_d38b31e6',
    category='Cloze',
    front='Ramsey fringe:  P(0|τ) = ______',
    back='P(0|τ) = [1 + e^{-τ/T₂*} cos(2πδτ + φ)] / 2  ·  Source: docs/07_quantum_hardware/04_benchmarking_and_characterization.md — Benchmarking and Characterization of Quantum Hardware',
)
