"""Card: cz_08_05_linear_systems_ea8e57cd

Generated by tools/gen_cloze.py from docs/08_advanced_topics/05_qsvt.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_05_linear_systems_ea8e57cd',
    category='Cloze',
    front='Linear systems:  P(x) ≈ ______',
    back='P(x) ≈ 1/x  ·  Source: docs/08_advanced_topics/05_qsvt.md — Quantum Singular Value Transformation',
)
