"""Card: cz_05_03_stabilizers_bit_flip_7d2e01fc

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/03_repetition_code.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_03_stabilizers_bit_flip_7d2e01fc',
    category='Cloze',
    front='Stabilizers (bit-flip):  g₁ = ______',
    back='g₁ = Z₁Z₂  ·  Source: docs/05_quantum_error_correction/03_repetition_code.md — The Quantum Repetition Code',
)
