"""Card: cz_01_07_crt_196aea53

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_crt_196aea53',
    category='Cloze',
    front='CRT:  x = ______',
    back='x = Σᵢ aᵢ Mᵢ (Mᵢ⁻¹ mod mᵢ) mod M  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
