"""Card: cz_05_02_bsc_capacity_082454ab

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/02_classical_error_correction.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_02_bsc_capacity_082454ab',
    category='Cloze',
    front='BSC capacity:  C = ______',
    back='C = 1 - H₂(p) = 1 + p log₂ p + (1-p) log₂(1-p)  ·  Source: docs/05_quantum_error_correction/02_classical_error_correction.md — Classical Error Correction',
)
