"""Card: cz_02_06_canonical_commutator_56ee6812

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_canonical_commutator_56ee6812',
    category='Cloze',
    front='Canonical commutator:  [x̂, p̂] = ______',
    back='[x̂, p̂] = iℏ  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
