"""Card: cz_06_02_uccsd_5525c72e

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/02_ansatz_design.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_02_uccsd_5525c72e',
    category='Cloze',
    front='UCCSD:  T = ______',
    back='T = T₁ + T₂  ·  Source: docs/06_variational_quantum_algorithms/02_ansatz_design.md — Ansatz Design',
)
