"""Card: cz_01_06_kl_divergence_pinsker_cherno_3b15c0de

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_kl_divergence_pinsker_cherno_3b15c0de',
    category='Cloze',
    front='KL divergence, Pinsker, Chernoff information:  C(P,Q) = ______',
    back='C(P,Q) = max_λ [−log₂ Σ p^λ q^{1−λ}]  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
