"""Card: cz_01_06_binomial_estimate_97926fdf

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_binomial_estimate_97926fdf',
    category='Cloze',
    front='Binomial estimate:  p̂ = ______',
    back='p̂ = K/N  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
