"""Card: cz_07_01_transmon_hamiltonian_0b60c6aa

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/01_superconducting_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_01_transmon_hamiltonian_0b60c6aa',
    category='Cloze',
    front='Transmon Hamiltonian:  H = ______',
    back='H = 4E_C n̂² - E_J cos φ̂  ·  Source: docs/07_quantum_hardware/01_superconducting_qubits.md — Superconducting Qubits',
)
