"""Card: cz_04_05_probability_of_success_3aa8ffd1

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/05_grover_search.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_05_probability_of_success_3aa8ffd1',
    category='Cloze',
    front='Probability of success:  P(x^*) = ______',
    back="P(x^*) = sin^2((2k+1)θ)  ·  Source: docs/04_quantum_algorithms/05_grover_search.md — Grover's Search Algorithm",
)
