"""Card: cz_03_02_phase_kickback_b39f3e03

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_02_phase_kickback_b39f3e03',
    category='Cloze',
    front='Phase kickback:  C_U (α|0⟩+β|1⟩)|u⟩ = ______',
    back='C_U (α|0⟩+β|1⟩)|u⟩ = (α|0⟩ + βe^{iφ}|1⟩)|u⟩  ·  Full entry: C_U (α|0⟩+β|1⟩)|u⟩ = (α|0⟩ + βe^{iφ}|1⟩)|u⟩  when U|u⟩ = e^{iφ}|u⟩  ·  Source: docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — Multi-Qubit Gates',
)
