"""Card: cz_05_05_transversal_gates_1c331961

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/05_css_codes_and_steane.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_05_transversal_gates_1c331961',
    category='Cloze',
    front='Transversal gates:  H̄ = ______',
    back='H̄ = H⊗7  ·  Source: docs/05_quantum_error_correction/05_css_codes_and_steane.md — CSS Codes and the Steane [[7,1,3]] Code',
)
