"""Card: cz_09_03_squared_loss_096c0b33

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/03_variational_classifiers.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_03_squared_loss_096c0b33',
    category='Cloze',
    front='Squared loss:  L(θ) = ______',
    back='L(θ) = (1/M) Σ_m (f(x_m, θ) - y_m)²  ·  Source: docs/09_quantum_machine_learning/03_variational_classifiers.md — Variational Quantum Classifiers',
)
