"""Card: cz_09_03_loss_gradient_fc84c18e

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/03_variational_classifiers.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_03_loss_gradient_fc84c18e',
    category='Cloze',
    front='Loss gradient:  ∂L/∂θ_k = ______',
    back='∂L/∂θ_k = (2/M) Σ_m (f(x_m, θ) - y_m) ∂f(x_m, θ)/∂θ_k  ·  Source: docs/09_quantum_machine_learning/03_variational_classifiers.md — Variational Quantum Classifiers',
)
