"""Card: cz_01_04_sign_of_a_permutation_0991d8c6

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_sign_of_a_permutation_0991d8c6',
    category='Cloze',
    front='Sign of a permutation:  sgn(σ) = ______',
    back='sgn(σ) = (-1)^{(number of transpositions)} = det(P_σ)  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
