"""Card: cz_07_05_linear_xeb_520999af

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_linear_xeb_520999af',
    category='Cloze',
    front='Linear XEB:  F_XEB = ______',
    back='F_XEB = (2ⁿ/N) Σᵢ p_C(xᵢ) - 1  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
