"""Card: cz_05_08_cat_qubit_noise_bias_dfecbc24

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/08_bosonic_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_08_cat_qubit_noise_bias_dfecbc24',
    category='Cloze',
    front='Cat qubit noise bias:  η = ______',
    back='η = p_Z/p_X ~ e^{2|α|²}  ·  Source: docs/05_quantum_error_correction/08_bosonic_codes.md — Bosonic Codes',
)
