"""Card: cz_01_06_expectation_and_variance_of_2199537a

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_expectation_and_variance_of_2199537a',
    category='Cloze',
    front='Expectation and variance of an observable:  ⟨M⟩ = ______',
    back='⟨M⟩ = ⟨ψ|M|ψ⟩  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
