"""Card: cz_01_05_tensor_products_1beb3cfc

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/05_representation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_05_tensor_products_1beb3cfc',
    category='Cloze',
    front='Tensor products:  χ_{V⊗W} = ______',
    back='χ_{V⊗W} = χ_V χ_W  ·  Source: docs/01_mathematical_foundations/05_representation_theory.md — Representation Theory for Quantum Computing',
)
