"""Card: cz_08_02_strong_subadditivity_b2c406cf

Generated by tools/gen_cloze.py from docs/08_advanced_topics/02_quantum_information_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_02_strong_subadditivity_b2c406cf',
    category='Cloze',
    front='Strong subadditivity:  S(ABC) + S(B) ≤ ______',
    back='S(ABC) + S(B) ≤ S(AB) + S(BC)  ·  Source: docs/08_advanced_topics/02_quantum_information_theory.md — Quantum Information Theory',
)
