"""Card: cz_01_09_homology_c31dba1e

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/09_topology_and_geometry.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_09_homology_c31dba1e',
    category='Cloze',
    front='Homology:  ∂₁∂₂ = ______',
    back='∂₁∂₂ = 0  ·  Source: docs/01_mathematical_foundations/09_topology_and_geometry.md — Topology and Geometry for Quantum Computing',
)
