"""Card: cz_06_04_cost_unitary_696f71bd

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/04_qaoa.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_04_cost_unitary_696f71bd',
    category='Cloze',
    front='Cost unitary:  U_C(γ) = ______',
    back='U_C(γ) = e^{-iγH_C} = ∏_{(ij)∈E} e^{-iγ(I-ZᵢZⱼ)/2}  ·  Source: docs/06_variational_quantum_algorithms/04_qaoa.md — QAOA: Quantum Approximate Optimization Algorithm',
)
