"""Card: cz_09_04_accuracy_standard_error_03e28e9c

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/04_qml_in_practice.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_04_accuracy_standard_error_03e28e9c',
    category='Cloze',
    front='Accuracy standard error:  SE = ______',
    back='SE = √(p(1-p)/M_test)  ·  Source: docs/09_quantum_machine_learning/04_qml_in_practice.md — QML in Practice: Claims, Evidence and Benchmarks',
)
