"""Card: cz_01_04_clifford_group_bde49960

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_clifford_group_bde49960',
    category='Cloze',
    front='Clifford group:  C_n = ______',
    back='C_n = {U : U P_n U† = P_n}  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
