"""Card: cz_07_05_effective_polarization_229e7ad1

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_effective_polarization_229e7ad1',
    category='Cloze',
    front='Effective polarization:  S = ______',
    back='S = [4ⁿ/(4ⁿ-1)] Σ_k (-1/2)^k h_k - 1/(4ⁿ-1)  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
