"""Card: cz_05_08_photon_number_spacing_for_bi_661323df

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/08_bosonic_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_08_photon_number_spacing_for_bi_661323df',
    category='Cloze',
    front='Photon number spacing for binomial codes:  S = ______',
    back='S = L + G + 1  ·  Source: docs/05_quantum_error_correction/08_bosonic_codes.md — Bosonic Codes',
)
