"""Card: cz_01_01_completeness_relation_3e903941

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/01_linear_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_01_completeness_relation_3e903941',
    category='Cloze',
    front='Completeness relation:  Σ_i |i⟩⟨i| = ______',
    back='Σ_i |i⟩⟨i| = I  ·  Full entry: Σ_i |i⟩⟨i| = I  for any orthonormal basis  ·  Source: docs/01_mathematical_foundations/01_linear_algebra.md — Linear Algebra for Quantum Computing',
)
