"""Card: cz_02_01_postulate_3_post_measurement_5c3a6c8b

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_01_postulate_3_post_measurement_5c3a6c8b',
    category='Cloze',
    front='Postulate 3 — Post-measurement state:  |ψ_m⟩ = ______',
    back='|ψ_m⟩ = M_m|ψ⟩/√(p(m))  ·  Source: docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — Postulates of Quantum Mechanics',
)
