"""Card: cz_02_10_jump_operators_71111fa1

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_jump_operators_71111fa1',
    category='Cloze',
    front='Jump operators:  L↓ = ______',
    back='L↓ = √(γ(n̄+1))σ₋  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
