"""Card: cz_01_09_fubini_study_metric_and_dist_0a524aa5

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/09_topology_and_geometry.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_09_fubini_study_metric_and_dist_0a524aa5',
    category='Cloze',
    front='Fubini-Study metric and distance:  d_FS = ______',
    back='d_FS = arccos|⟨ψ|φ⟩|  ·  Source: docs/01_mathematical_foundations/09_topology_and_geometry.md — Topology and Geometry for Quantum Computing',
)
