"""Card: cz_01_07_gaussian_uncertainty_d42d194b

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_gaussian_uncertainty_d42d194b',
    category='Cloze',
    front='Gaussian uncertainty:  σₓσₖ = ______',
    back='σₓσₖ = ½  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
