"""Card: cz_05_01_no_cloning_impossibility_a0131183

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/01_why_qec_is_hard.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_01_no_cloning_impossibility_a0131183',
    category='Cloze',
    front='No-cloning impossibility:  U|ψ⟩|0⟩ = ______',
    back='U|ψ⟩|0⟩ = |ψ⟩|ψ⟩  ·  Source: docs/05_quantum_error_correction/01_why_qec_is_hard.md — Why Quantum Error Correction Is Hard',
)
