"""Card: cz_01_04_lie_algebra_of_su_2_eafc82e7

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_lie_algebra_of_su_2_eafc82e7',
    category='Cloze',
    front='Lie algebra of SU(2):  [σ_j/2, σ_k/2] = ______',
    back='[σ_j/2, σ_k/2] = i ε_{jkl} σ_l/2  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
