"""Card: cz_09_03_encoding_induced_plateau_mea_e2b39da8

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/03_variational_classifiers.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_03_encoding_induced_plateau_mea_e2b39da8',
    category='Cloze',
    front='Encoding-induced plateau (measured):  Var[∂f/∂θ] ∝ ______',
    back='Var[∂f/∂θ] ∝ 2^{-0.99 n}  ·  Source: docs/09_quantum_machine_learning/03_variational_classifiers.md — Variational Quantum Classifiers',
)
