"""Card: cz_05_02_hamming_distance_82a3efb4

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/02_classical_error_correction.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_02_hamming_distance_82a3efb4',
    category='Cloze',
    front='Hamming distance:  d_H(u,v) = ______',
    back='d_H(u,v) = wt(u ⊕ v)  ·  Source: docs/05_quantum_error_correction/02_classical_error_correction.md — Classical Error Correction',
)
