"""Card: cz_04_01_quantum_parallelism_function_5c1fedac

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_01_quantum_parallelism_function_5c1fedac',
    category='Cloze',
    front='Quantum parallelism (function evaluation):  O_f(1/√(2^n) Σ_x|x⟩)|0⟩ = ______',
    back='O_f(1/√(2^n) Σ_x|x⟩)|0⟩ = 1/√(2^n) Σ_x|x⟩|f(x)⟩  ·  Source: docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — Quantum Parallelism and Interference',
)
