"""Card: cz_02_06_position_momentum_overlap_db9d4426

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_position_momentum_overlap_db9d4426',
    category='Cloze',
    front='Position/momentum overlap:  ⟨x|p⟩ = ______',
    back='⟨x|p⟩ = e^{ipx/ℏ}/√(2πℏ)  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
