"""Card: cz_04_04_energy_estimation_precision_7e1eb7fc

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/04_quantum_phase_estimation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_04_energy_estimation_precision_7e1eb7fc',
    category='Cloze',
    front='Energy estimation precision:  δE = ______',
    back='δE = 2π/(τ · 2^n)  ·  Source: docs/04_quantum_algorithms/04_quantum_phase_estimation.md — Quantum Phase Estimation',
)
