"""Card: cz_03_02_error_propagation_through_cn_fb2a519c

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_02_error_propagation_through_cn_fb2a519c',
    category='Cloze',
    front='Error propagation through CNOT:  CNOT(X⊗I)CNOT = ______',
    back='CNOT(X⊗I)CNOT = X⊗X  ·  Full entry: CNOT(X⊗I)CNOT = X⊗X,  CNOT(I⊗Z)CNOT = Z⊗Z  ·  Source: docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — Multi-Qubit Gates',
)
