"""Card: cz_04_04_measurement_outcome_3bc0d6c1

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/04_quantum_phase_estimation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_04_measurement_outcome_3bc0d6c1',
    category='Cloze',
    front='Measurement outcome:  j* = ______',
    back='j* = round(2^nφ)  ·  Source: docs/04_quantum_algorithms/04_quantum_phase_estimation.md — Quantum Phase Estimation',
)
