"""Card: cz_01_01_inner_product_cn_5ff43cf5

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/01_linear_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_01_inner_product_cn_5ff43cf5',
    category='Cloze',
    front='Inner product (ℂⁿ):  ⟨u|v⟩ = ______',
    back='⟨u|v⟩ = Σ_{i=1}^n u_i^* v_i  ·  Source: docs/01_mathematical_foundations/01_linear_algebra.md — Linear Algebra for Quantum Computing',
)
