"""Card: cz_05_01_syndrome_measurement_eigenva_3da07adc

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/01_why_qec_is_hard.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_01_syndrome_measurement_eigenva_3da07adc',
    category='Cloze',
    front='Syndrome measurement eigenvalue:  g|ψ_err⟩ = ______',
    back='g|ψ_err⟩ = ±|ψ_err⟩  ·  Source: docs/05_quantum_error_correction/01_why_qec_is_hard.md — Why Quantum Error Correction Is Hard',
)
