"""Card: cz_03_01_clifford_conjugation_h_c0ae1759

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/01_single_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_01_clifford_conjugation_h_c0ae1759',
    category='Cloze',
    front='Clifford conjugation (H):  HXH = ______',
    back='HXH = Z  ·  Full entry: HXH = Z,  HZH = X,  HYH = -Y  ·  Source: docs/03_quantum_gates_and_circuits/01_single_qubit_gates.md — Single-Qubit Gates',
)
