"""Card: cz_02_07_ladder_algebra_9e59574b

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_ladder_algebra_9e59574b',
    category='Cloze',
    front='Ladder algebra:  [â,â†] = ______',
    back='[â,â†] = 1  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
