"""Card: cz_02_02_bloch_vector_components_6597d538

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_02_bloch_vector_components_6597d538',
    category='Cloze',
    front='Bloch vector components:  r_x = ______',
    back='r_x = ⟨X⟩ = sinθ cosϕ  ·  Full entry: r_x = ⟨X⟩ = sinθ cosϕ,  r_y = ⟨Y⟩ = sinθ sinϕ,  r_z = ⟨Z⟩ = cosθ  ·  Source: docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — Qubits and the Bloch Sphere',
)
