"""Card: cz_08_05_qsp_sequence_3b8d2098

Generated by tools/gen_cloze.py from docs/08_advanced_topics/05_qsvt.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_05_qsp_sequence_3b8d2098',
    category='Cloze',
    front='QSP sequence:  U_φ(x) = ______',
    back='U_φ(x) = e^{iφ₀Z} Π_{j=1}^{d} [W(x) e^{iφⱼZ}]  ·  Source: docs/08_advanced_topics/05_qsvt.md — Quantum Singular Value Transformation',
)
