"""Card: cz_08_05_hamiltonian_simulation_330bad0a

Generated by tools/gen_cloze.py from docs/08_advanced_topics/05_qsvt.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_05_hamiltonian_simulation_330bad0a',
    category='Cloze',
    front='Hamiltonian simulation:  d = ______',
    back='d = O(λt + log(1/ε))  ·  Source: docs/08_advanced_topics/05_qsvt.md — Quantum Singular Value Transformation',
)
