"""Card: cz_06_04_p_1_approximation_ratio_3_re_5fdb33b3

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/04_qaoa.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_04_p_1_approximation_ratio_3_re_5fdb33b3',
    category='Cloze',
    front='p=1 approximation ratio (3-regular MaxCut):  r₁ = ______',
    back='r₁ = 0.6924  ·  Source: docs/06_variational_quantum_algorithms/04_qaoa.md — QAOA: Quantum Approximate Optimization Algorithm',
)
