"""Card: cz_01_06_optimal_shot_allocation_for_f35ea156

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_optimal_shot_allocation_for_f35ea156',
    category='Cloze',
    front='Optimal shot allocation for H = Σ cᵢPᵢ (derived below):  Sᵢ ∝ ______',
    back='Sᵢ ∝ |cᵢ|σᵢ  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
