"""Card: cz_04_09_element_distinctness_johnson_96fe775d

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/09_quantum_walks.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_09_element_distinctness_johnson_96fe775d',
    category='Cloze',
    front='Element distinctness (Johnson graph, subset size r):  Q = ______',
    back='Q = Θ(N^{2/3})  ·  Full entry: Q(r) ≈ r + N/√r ⇒ r^* = (N/2)^{2/3}, Q = Θ(N^{2/3})  ·  Source: docs/04_quantum_algorithms/09_quantum_walks.md — Quantum Walks',
)
