"""Card: cz_05_03_stabilizers_phase_flip_0c6dab04

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/03_repetition_code.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_03_stabilizers_phase_flip_0c6dab04',
    category='Cloze',
    front='Stabilizers (phase-flip):  g₁ = ______',
    back='g₁ = X₁X₂  ·  Source: docs/05_quantum_error_correction/03_repetition_code.md — The Quantum Repetition Code',
)
