"""Card: cz_01_02_global_phase_irrelevance_b7cee723

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_02_global_phase_irrelevance_b7cee723',
    category='Cloze',
    front='Global phase irrelevance:  |e^{iθ}ψ⟩ ≡ ______',
    back='|e^{iθ}ψ⟩ ≡ |ψ⟩  ·  Full entry: |e^{iθ}ψ⟩ ≡ |ψ⟩  (physically identical)  ·  Source: docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — Complex Numbers and Hilbert Spaces',
)
