"""Card: cz_02_05_von_neumann_entropy_684f8fe4

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_05_von_neumann_entropy_684f8fe4',
    category='Cloze',
    front='Von Neumann entropy:  S(ρ) = ______',
    back='S(ρ) = -Tr(ρ log_2ρ) = -Σ_i λ_i log_2 λ_i  ·  Source: docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — Density Matrices and Open Systems',
)
