"""Card: cz_09_01_measured_state_prep_cost_01a133c1

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/01_data_encoding.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_01_measured_state_prep_cost_01a133c1',
    category='Cloze',
    front='Measured state-prep cost:  CNOT(n) = ______',
    back='CNOT(n) = 2ⁿ - n - 1  ·  Source: docs/09_quantum_machine_learning/01_data_encoding.md — Data Encoding and Quantum Feature Maps',
)
