"""Card: cz_02_06_probability_current_b7becb92

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_probability_current_b7becb92',
    category='Cloze',
    front='Probability current:  j = ______',
    back='j = (ℏ/m) Im[ψ* ∂ψ/∂x]  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
