"""Card: cz_01_08_schro_dinger_solution_and_dy_0a24511a

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_08_schro_dinger_solution_and_dy_0a24511a',
    category='Cloze',
    front='Schrödinger solution and Dyson series:  U(t) = ______',
    back='U(t) = e^{-iHt/ℏ}  ·  Source: docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — Analysis for Quantum Mechanics',
)
