"""Card: cz_05_09_css_check_f3d08fb4

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/09_qldpc_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_09_css_check_f3d08fb4',
    category='Cloze',
    front='CSS check:  H_X H_Zᵀ = ______',
    back='H_X H_Zᵀ = H₁ ⊗ H₂ᵀ + H₁ ⊗ H₂ᵀ = 0 (mod 2)  ·  Source: docs/05_quantum_error_correction/09_qldpc_codes.md — Quantum LDPC Codes',
)
