"""Card: cz_06_03_qfim_pure_state_f3dd8d7b

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_03_qfim_pure_state_f3dd8d7b',
    category='Cloze',
    front='QFIM (pure state):  F_{ij} = ______',
    back='F_{ij} = 4 Re[⟨∂ᵢψ|∂ⱼψ⟩ - ⟨∂ᵢψ|ψ⟩⟨ψ|∂ⱼψ⟩]  ·  Source: docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — The Parameter-Shift Rule and Quantum Gradients',
)
