"""Card: cz_02_01_postulate_4_tensor_product_b1300c33

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_01_postulate_4_tensor_product_b1300c33',
    category='Cloze',
    front='Postulate 4 — Tensor product:  H_{12} = ______',
    back='H_{12} = H_1 ⊗ H_2  ·  Full entry: H_{12} = H_1 ⊗ H_2,  dim = dim(H_1) · dim(H_2)  ·  Source: docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — Postulates of Quantum Mechanics',
)
