"""Card: cz_01_06_shannon_binary_conditional_m_8d1b757b

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_shannon_binary_conditional_m_8d1b757b',
    category='Cloze',
    front='Shannon, binary, conditional, mutual:  H(X) = ______',
    back='H(X) = −Σ p log₂ p  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
