"""Card: cz_02_09_first_order_a023bbcd

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/09_perturbation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_09_first_order_a023bbcd',
    category='Cloze',
    front='First order:  E_n¹ = ______',
    back='E_n¹ = ⟨n⁰|V̂|n⁰⟩  ·  Source: docs/02_quantum_mechanics/09_perturbation_theory.md — Perturbation Theory and Driven Systems',
)
