"""Card: cz_06_06_pec_quasi_probability_d7fd6817

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_06_pec_quasi_probability_d7fd6817',
    category='Cloze',
    front='PEC quasi-probability:  G_ideal = ______',
    back='G_ideal = Σᵢ qᵢ Bᵢ  ·  Source: docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — Noise and Error Mitigation in NISQ Algorithms',
)
