"""Card: cz_07_05_coherent_over_rotation_d595eb4a

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_coherent_over_rotation_d595eb4a',
    category='Cloze',
    front='Coherent over-rotation:  ½‖U-I‖_◇ = ______',
    back='½‖U-I‖_◇ = |sin(θ/2)|  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
