"""Card: cz_04_01_phase_kickback_49378273

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_01_phase_kickback_49378273',
    category='Cloze',
    front='Phase kickback:  (CU)|+⟩|u⟩ = ______',
    back='(CU)|+⟩|u⟩ = (|0⟩ + e^{iφ}|1⟩)/√2|u⟩  ·  Full entry: (CU)|+⟩|u⟩ = (|0⟩ + e^{iφ}|1⟩)/√2|u⟩  when U|u⟩ = e^{iφ}|u⟩  ·  Source: docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — Quantum Parallelism and Interference',
)
