"""Card: cz_09_01_feature_map_and_fidelity_ker_f9060d46

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/01_data_encoding.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_01_feature_map_and_fidelity_ker_f9060d46',
    category='Cloze',
    front='Feature map and fidelity kernel:  |φ(x)⟩ = ______',
    back='|φ(x)⟩ = U_φ(x)|0⟩^{⊗n}  ·  Source: docs/09_quantum_machine_learning/01_data_encoding.md — Data Encoding and Quantum Feature Maps',
)
