"""Card: cz_07_01_josephson_relations_1dc1d638

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/01_superconducting_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_01_josephson_relations_1dc1d638',
    category='Cloze',
    front='Josephson relations:  I = ______',
    back='I = I_c sinφ  ·  Source: docs/07_quantum_hardware/01_superconducting_qubits.md — Superconducting Qubits',
)
