"""Card: cz_01_07_convergents_6294a504

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_convergents_6294a504',
    category='Cloze',
    front='Convergents:  pₖ = ______',
    back='pₖ = aₖp_{k−1} + p_{k−2}  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
