"""Card: cz_07_03_rydberg_blockade_radius_71bc435c

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/03_photonic_and_other_platforms.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_03_rydberg_blockade_radius_71bc435c',
    category='Cloze',
    front='Rydberg blockade radius:  r_b = ______',
    back='r_b = (C₆/Ω)^{1/6}  ·  Source: docs/07_quantum_hardware/03_photonic_and_other_platforms.md — Photonic and Other Quantum Computing Platforms',
)
