"""Card: cz_08_04_majorana_representation_of_t_065b23bb

Generated by tools/gen_cloze.py from docs/08_advanced_topics/04_topological_quantum_computation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_04_majorana_representation_of_t_065b23bb',
    category='Cloze',
    front='Majorana representation of the braid:  B₁₂ = ______',
    back='B₁₂ = exp(π γ₁γ₂/4) = (1 + γ₁γ₂)/√2  ·  Source: docs/08_advanced_topics/04_topological_quantum_computation.md — Topological Quantum Computation',
)
