"""Card: cz_04_03_qft_definition_18481161

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/03_quantum_fourier_transform.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_03_qft_definition_18481161',
    category='Cloze',
    front='QFT definition:  QFT|j⟩ = ______',
    back='QFT|j⟩ = 1/√N Σ_{k=0}^{N-1}e^{2πijk/N}|k⟩  ·  Source: docs/04_quantum_algorithms/03_quantum_fourier_transform.md — Quantum Fourier Transform',
)
