"""Card: cz_04_08_intercept_resend_random_bb84_06f40c4e

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/08_quantum_cryptography.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_08_intercept_resend_random_bb84_06f40c4e',
    category='Cloze',
    front='Intercept-resend (random BB84 basis):  QBER = ______',
    back='QBER = 1/4  ·  Full entry: QBER = 1/4,  I(A:E) = 1/2 bit/sifted bit,  P(Eve guesses bit) = 3/4  ·  Source: docs/04_quantum_algorithms/08_quantum_cryptography.md — Quantum Cryptography',
)
