"""Card: cz_01_07_be_zout_a26ccf8a

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_be_zout_a26ccf8a',
    category='Cloze',
    front='Bézout:  sa + tb = ______',
    back='sa + tb = gcd(a, b)  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
