"""Card: cz_01_04_single_qubit_rotation_634e0da8

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_single_qubit_rotation_634e0da8',
    category='Cloze',
    front='Single-qubit rotation:  e^{-iθ n̂·σ/2} = ______',
    back='e^{-iθ n̂·σ/2} = cos(θ/2) I - i sin(θ/2) n̂·σ  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
