"""Card: cz_06_07_gate_fidelity_2cfa1b84

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_07_gate_fidelity_2cfa1b84',
    category='Cloze',
    front='Gate fidelity:  F = ______',
    back='F = |Tr[U_target† U(T)]|² / d²  ·  Source: docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — Quantum Optimal Control',
)
