"""Card: cz_06_03_hessian_shift_54d21138

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_03_hessian_shift_54d21138',
    category='Cloze',
    front='Hessian shift:  ∂²f/∂θᵢ∂θⱼ = ______',
    back='∂²f/∂θᵢ∂θⱼ = [f(++) - f(+-) - f(-+) + f(--)]/4  ·  Source: docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — The Parameter-Shift Rule and Quantum Gradients',
)
