"""Card: cz_01_07_dft_656df365

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_dft_656df365',
    category='Cloze',
    front='DFT:  F_{kj} = ______',
    back='F_{kj} = ω^{jk}/√N  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
