"""Card: cz_07_01_qubit_frequency_80d11aa1

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/01_superconducting_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_01_qubit_frequency_80d11aa1',
    category='Cloze',
    front='Qubit frequency:  ω₀₁ ≈ ______',
    back='ω₀₁ ≈ √(8 E_J E_C) / ℏ  ·  Source: docs/07_quantum_hardware/01_superconducting_qubits.md — Superconducting Qubits',
)
