"""Card: cz_04_02_bernstein_vazirani_amplitude_f6744a36

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/02_deutsch_jozsa_and_bernstein_vazirani.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_02_bernstein_vazirani_amplitude_f6744a36',
    category='Cloze',
    front='Bernstein-Vazirani: amplitude after H^n:  amp(y) = ______',
    back='amp(y) = [y = s]  ·  Source: docs/04_quantum_algorithms/02_deutsch_jozsa_and_bernstein_vazirani.md — Deutsch-Jozsa and Bernstein-Vazirani',
)
