"""Card: cz_02_07_coherent_state_ea46a86c

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_coherent_state_ea46a86c',
    category='Cloze',
    front='Coherent state:  â|α⟩ = ______',
    back='â|α⟩ = α|α⟩  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
