"""Card: cz_01_09_lie_group_geometry_81e3f537

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/09_topology_and_geometry.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_09_lie_group_geometry_81e3f537',
    category='Cloze',
    front='Lie group geometry:  T_I SU(2) = ______',
    back='T_I SU(2) = su(2) = span{iX, iY, iZ}  ·  Source: docs/01_mathematical_foundations/09_topology_and_geometry.md — Topology and Geometry for Quantum Computing',
)
