"""Card: cz_02_01_postulate_2_schro_dinger_equ_f3f56249

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_01_postulate_2_schro_dinger_equ_f3f56249',
    category='Cloze',
    front='Postulate 2 — Schrödinger equation:  iℏ d/dt|ψ(t)⟩ = ______',
    back='iℏ d/dt|ψ(t)⟩ = H|ψ(t)⟩  ·  Source: docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — Postulates of Quantum Mechanics',
)
