"""Card: cz_02_05_purity_bf8b81ea

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_05_purity_bf8b81ea',
    category='Cloze',
    front='Purity:  Tr(ρ^2) = ______',
    back='Tr(ρ^2) = Σ_i λ_i^2  ·  Full entry: Tr(ρ^2) = Σ_i λ_i^2,  1/d ≤ Tr(ρ^2) ≤ 1  ·  Source: docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — Density Matrices and Open Systems',
)
