"""Card: cz_02_10_fidelity_squared_convention_4419c248

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_fidelity_squared_convention_4419c248',
    category='Cloze',
    front='Fidelity (squared convention):  F(ρ,σ) = ______',
    back='F(ρ,σ) = (Tr√(√ρ σ √ρ))²  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
