"""Card: cz_02_07_fock_state_moments_2554c8ab

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_fock_state_moments_2554c8ab',
    category='Cloze',
    front='Fock-state moments:  ⟨x̂⟩ = ______',
    back='⟨x̂⟩ = ⟨p̂⟩ = 0  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
