"""Card: cz_07_05_polarization_from_process_in_ac366824

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_polarization_from_process_in_ac366824',
    category='Cloze',
    front='Polarization from process infidelity ε:  γ = ______',
    back='γ = 1 - 4ⁿ ε/(4ⁿ - 1)  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
