"""Card: cz_05_04_graph_state_stabilizer_2fe4912a

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/04_stabilizer_formalism.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_04_graph_state_stabilizer_2fe4912a',
    category='Cloze',
    front='Graph state stabilizer:  K_v = ______',
    back='K_v = X_v ⊗ (⊗_{u∈N(v)} Z_u)  ·  Source: docs/05_quantum_error_correction/04_stabilizer_formalism.md — The Stabilizer Formalism',
)
