"""Card: cz_03_01_gate_hierarchy_5714f7cd

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/01_single_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_01_gate_hierarchy_5714f7cd',
    category='Cloze',
    front='Gate hierarchy:  T^2 = ______',
    back='T^2 = S  ·  Full entry: T^2 = S,  S^2 = Z,  Z^2 = I,  T^8 = I  ·  Source: docs/03_quantum_gates_and_circuits/01_single_qubit_gates.md — Single-Qubit Gates',
)
