"""Card: cz_05_08_cat_qubit_logical_states_2d6e4bb0

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/08_bosonic_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_08_cat_qubit_logical_states_2d6e4bb0',
    category='Cloze',
    front='Cat qubit logical states:  |±_L⟩ = ______',
    back='|±_L⟩ = N±(|α⟩ ± |-α⟩)  ·  Source: docs/05_quantum_error_correction/08_bosonic_codes.md — Bosonic Codes',
)
