"""Card: cz_01_02_projection_operator_eb40d32c

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_02_projection_operator_eb40d32c',
    category='Cloze',
    front='Projection operator:  P_W = ______',
    back='P_W = Σ_{i ∈ basis of W} |e_i⟩⟨e_i|  ·  Full entry: P_W = Σ_{i ∈ basis of W} |e_i⟩⟨e_i|,  P_W^2 = P_W,  P_W† = P_W  ·  Source: docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — Complex Numbers and Hilbert Spaces',
)
