"""Card: cz_06_06_virtual_distillation_1e477c19

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_06_virtual_distillation_1e477c19',
    category='Cloze',
    front='Virtual distillation:  ⟨O⟩_VD = ______',
    back='⟨O⟩_VD = Tr[Oρ^M]/Tr[ρ^M]  ·  Source: docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — Noise and Error Mitigation in NISQ Algorithms',
)
