"""Card: cz_01_08_fourier_transform_is_unitary_4cfa8f84

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_08_fourier_transform_is_unitary_4cfa8f84',
    category='Cloze',
    front='Fourier transform is unitary:  ‖Fψ‖₂ = ______',
    back='‖Fψ‖₂ = ‖ψ‖₂  ·  Source: docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — Analysis for Quantum Mechanics',
)
