"""Card: cz_04_05_state_after_k_iterations_c0ef8646

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/05_grover_search.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_05_state_after_k_iterations_c0ef8646',
    category='Cloze',
    front='State after k iterations:  G^k|s⟩ = ______',
    back="G^k|s⟩ = sin((2k+1)θ)|x^*⟩ + cos((2k+1)θ)|s'⟩  ·  Source: docs/04_quantum_algorithms/05_grover_search.md — Grover's Search Algorithm",
)
