"""Card: cz_06_05_local_cost_threshold_d0507b60

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/05_barren_plateaus.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_05_local_cost_threshold_d0507b60',
    category='Cloze',
    front='Local cost threshold:  Var ∝ ______',
    back='Var ∝ 1/poly(n)  ·  Source: docs/06_variational_quantum_algorithms/05_barren_plateaus.md — Barren Plateaus',
)
