"""Card: cz_09_02_kernel_expansion_fbe58c7d

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/02_quantum_kernels.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_02_kernel_expansion_fbe58c7d',
    category='Cloze',
    front='Kernel expansion:  f(x) = ______',
    back='f(x) = sign(Σ_m α_m k(x_m, x) + b)  ·  Source: docs/09_quantum_machine_learning/02_quantum_kernels.md — Quantum Kernel Methods',
)
