"""Card: cz_02_04_entanglement_entropy_c47af650

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_04_entanglement_entropy_c47af650',
    category='Cloze',
    front='Entanglement entropy:  S = ______',
    back='S = -Tr(ρ_A log_2 ρ_A) = -Σ_i λ_i^2 log_2 λ_i^2  ·  Source: docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — Entanglement and Nonlocality',
)
