"""Card: cz_07_05_process_fidelity_from_a_dire_3defabfb

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_process_fidelity_from_a_dire_3defabfb',
    category='Cloze',
    front='Process fidelity from a direct-RB decay:  F = ______',
    back='F = [1 + (d²-1)α]/d²  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
