"""Card: cz_01_02_born_rule_via_projector_803f1cc8

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_02_born_rule_via_projector_803f1cc8',
    category='Cloze',
    front='Born rule via projector:  Prob(m) = ______',
    back='Prob(m) = ⟨ψ|P_m|ψ⟩  ·  Source: docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — Complex Numbers and Hilbert Spaces',
)
