"""Card: cz_05_09_bpt_bound_2d_local_codes_49db02a6

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/09_qldpc_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_09_bpt_bound_2d_local_codes_49db02a6',
    category='Cloze',
    front='BPT bound (2D local codes):  k d² = ______',
    back='k d² = O(n)  ·  Source: docs/05_quantum_error_correction/09_qldpc_codes.md — Quantum LDPC Codes',
)
