"""Card: cz_07_03_nv_zero_field_splitting_c9d05d8d

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/03_photonic_and_other_platforms.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_03_nv_zero_field_splitting_c9d05d8d',
    category='Cloze',
    front='NV zero-field splitting:  D/2π = ______',
    back='D/2π = 2.87 GHz  ·  Source: docs/07_quantum_hardware/03_photonic_and_other_platforms.md — Photonic and Other Quantum Computing Platforms',
)
