"""Card: cz_06_05_mean_gradient_73e1394e

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/05_barren_plateaus.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_05_mean_gradient_73e1394e',
    category='Cloze',
    front='Mean gradient:  E_θ[∂C/∂θᵢ] = ______',
    back='E_θ[∂C/∂θᵢ] = 0  ·  Source: docs/06_variational_quantum_algorithms/05_barren_plateaus.md — Barren Plateaus',
)
