"""Card: cz_09_02_fidelity_quantum_kernel_bd98b15e

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/02_quantum_kernels.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_02_fidelity_quantum_kernel_bd98b15e',
    category='Cloze',
    front="Fidelity quantum kernel:  K_Q(x,x') = ______",
    back="K_Q(x,x') = |⟨φ(x)|φ(x')⟩|² = Tr[ρ(x)ρ(x')]  ·  Source: docs/09_quantum_machine_learning/02_quantum_kernels.md — Quantum Kernel Methods",
)
