"""Card: cz_02_06_infinite_well_5b6adf93

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_infinite_well_5b6adf93',
    category='Cloze',
    front='Infinite well:  E_n = ______',
    back='E_n = n²π²ℏ²/(2mL²)  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
