"""Card: cz_01_07_euler_fermat_a9b278e6

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_euler_fermat_a9b278e6',
    category='Cloze',
    front='Euler / Fermat:  φ(pq) = ______',
    back='φ(pq) = (p−1)(q−1)  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
