"""Card: cz_03_03_solovay_kitaev_gate_count_fc59937e

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/03_circuit_model_and_universality.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_03_solovay_kitaev_gate_count_fc59937e',
    category='Cloze',
    front='Solovay-Kitaev gate count:  Gates(ε) = ______',
    back='Gates(ε) = O(log^c(1/ε))  ·  Full entry: Gates(ε) = O(log^c(1/ε)),  c ≈ 3.97 (original), ≈ 1.44 (Kuperberg, best known generic)  ·  Source: docs/03_quantum_gates_and_circuits/03_circuit_model_and_universality.md — Circuit Model and Universality',
)
