"""Card: cz_08_03_tfim_782d104a

Generated by tools/gen_cloze.py from docs/08_advanced_topics/03_many_body_physics_and_simulation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_03_tfim_782d104a',
    category='Cloze',
    front='TFIM:  H = ______',
    back='H = -J Σ ZᵢZⱼ - h Σ Xᵢ  ·  Source: docs/08_advanced_topics/03_many_body_physics_and_simulation.md — Many-Body Physics and Quantum Simulation',
)
