"""Card: cz_06_07_control_hamiltonian_afa2a296

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_07_control_hamiltonian_afa2a296',
    category='Cloze',
    front='Control Hamiltonian:  H(t) = ______',
    back='H(t) = H₀ + Σₖ uₖ(t) Hₖ  ·  Source: docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — Quantum Optimal Control',
)
