"""Card: cz_04_08_chsh_certificate_e91_3f3fbb7b

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/08_quantum_cryptography.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_08_chsh_certificate_e91_3f3fbb7b',
    category='Cloze',
    front='CHSH certificate (E91):  S_quantum = ______',
    back='S_quantum = 2√2  ·  Source: docs/04_quantum_algorithms/08_quantum_cryptography.md — Quantum Cryptography',
)
