"""Card: cz_02_04_chsh_operator_3b64ca3f

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_04_chsh_operator_3b64ca3f',
    category='Cloze',
    front='CHSH operator:  S = ______',
    back='S = A_1 ⊗ B_1 + A_1 ⊗ B_2 + A_2 ⊗ B_1 - A_2 ⊗ B_2  ·  Source: docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — Entanglement and Nonlocality',
)
