"""Card: cz_05_09_hypergraph_product_1a102e0b

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/09_qldpc_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_09_hypergraph_product_1a102e0b',
    category='Cloze',
    front='Hypergraph product:  H_X = ______',
    back='H_X = [H₁ ⊗ I | I ⊗ H₂ᵀ]  ·  Source: docs/05_quantum_error_correction/09_qldpc_codes.md — Quantum LDPC Codes',
)
