"""Card: cz_06_01_measurement_variance_bfa7edef

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_01_measurement_variance_bfa7edef',
    category='Cloze',
    front='Measurement variance:  Var(E) ≤ ______',
    back='Var(E) ≤ (Σ_i |c_i|)² M / (4S)  ·  Source: docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — VQE Fundamentals',
)
