"""Card: cz_06_03_general_generator_82b69be8

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_03_general_generator_82b69be8',
    category='Cloze',
    front='General generator:  ∂f/∂θᵢ = ______',
    back='∂f/∂θᵢ = r[f(θ + π/(4r) eᵢ) - f(θ - π/(4r) eᵢ)]  ·  Source: docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — The Parameter-Shift Rule and Quantum Gradients',
)
