"""Card: cz_07_02_ms_gate_unitary_c206909c

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/02_trapped_ion_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_02_ms_gate_unitary_c206909c',
    category='Cloze',
    front='MS gate unitary:  U_MS(π/4) = ______',
    back='U_MS(π/4) = exp(-iπ/4 · XX)  ·  Source: docs/07_quantum_hardware/02_trapped_ion_qubits.md — Trapped Ion Qubits',
)
