"""Card: cz_07_04_t1_decay_0708396e

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/04_benchmarking_and_characterization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_04_t1_decay_0708396e',
    category='Cloze',
    front='T₁ decay:  P(1|τ) = ______',
    back='P(1|τ) = A e^{-τ/T₁} + B  ·  Source: docs/07_quantum_hardware/04_benchmarking_and_characterization.md — Benchmarking and Characterization of Quantum Hardware',
)
