"""Card: cz_07_03_kitaev_majorana_wire_115839f6

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/03_photonic_and_other_platforms.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_03_kitaev_majorana_wire_115839f6',
    category='Cloze',
    front='Kitaev Majorana wire:  {γᵢ, γⱼ} = ______',
    back='{γᵢ, γⱼ} = 2δᵢⱼ  ·  Source: docs/07_quantum_hardware/03_photonic_and_other_platforms.md — Photonic and Other Quantum Computing Platforms',
)
