"""Card: cz_07_02_jaynes_cummings_hamiltonian_fb7bf0ab

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/02_trapped_ion_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_02_jaynes_cummings_hamiltonian_fb7bf0ab',
    category='Cloze',
    front='Jaynes-Cummings Hamiltonian (sideband):  H = ______',
    back='H = ℏΩη(aσ₊ + a†σ₋)  ·  Source: docs/07_quantum_hardware/02_trapped_ion_qubits.md — Trapped Ion Qubits',
)
