"""Card: cz_01_05_characters_of_z_n_are_the_qf_98d4460d

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/05_representation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_05_characters_of_z_n_are_the_qf_98d4460d',
    category='Cloze',
    front='Characters of ℤ_N are the QFT:  χ_k(j) = ______',
    back='χ_k(j) = e^{2πijk/N}  ·  Source: docs/01_mathematical_foundations/05_representation_theory.md — Representation Theory for Quantum Computing',
)
