"""Card: cz_01_06_born_rule_56ebb713

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_born_rule_56ebb713',
    category='Cloze',
    front='Born rule:  P(x) = ______',
    back='P(x) = |⟨x|ψ⟩|²  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
