"""Card: cz_01_09_braid_relations_3dd90843

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/09_topology_and_geometry.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_09_braid_relations_3dd90843',
    category='Cloze',
    front='Braid relations:  σᵢσᵢ₊₁σᵢ = ______',
    back='σᵢσᵢ₊₁σᵢ = σᵢ₊₁σᵢσᵢ₊₁  ·  Source: docs/01_mathematical_foundations/09_topology_and_geometry.md — Topology and Geometry for Quantum Computing',
)
