"""Card: cz_04_09_dispersion_and_spreading_had_23c953c2

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/09_quantum_walks.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_09_dispersion_and_spreading_had_23c953c2',
    category='Cloze',
    front='Dispersion and spreading (Hadamard walk on the line):  sinω(k) = ______',
    back='sinω(k) = (sin k)/√2  ·  Full entry: sinω(k) = (sin k)/√2,  |v_g|≤ 1/√2,  σ_{qu} → √(1-1/√2) t ≈ 0.54 t,  σ_{cl} = √t  ·  Source: docs/04_quantum_algorithms/09_quantum_walks.md — Quantum Walks',
)
