"""Card: cz_02_03_povm_probabilities_a4b19a28

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/03_quantum_measurements.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_03_povm_probabilities_a4b19a28',
    category='Cloze',
    front='POVM probabilities:  p(m) = ______',
    back='p(m) = Tr(E_mρ)  ·  Full entry: p(m) = Tr(E_mρ),  E_m ≥ 0,  Σ_m E_m = I  ·  Source: docs/02_quantum_mechanics/03_quantum_measurements.md — Quantum Measurements',
)
