"""Card: cz_03_02_cz_cnot_relation_52e4a2d0

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_02_cz_cnot_relation_52e4a2d0',
    category='Cloze',
    front='CZ-CNOT relation:  CNOT = ______',
    back='CNOT = (I⊗H) CZ (I⊗H)  ·  Source: docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — Multi-Qubit Gates',
)
