"""Card: cz_05_08_gkp_stabilizers_1d3fdf55

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/08_bosonic_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_08_gkp_stabilizers_1d3fdf55',
    category='Cloze',
    front='GKP stabilizers:  S_q = ______',
    back='S_q = e^{i2√π q̂}  ·  Source: docs/05_quantum_error_correction/08_bosonic_codes.md — Bosonic Codes',
)
