"""Card: cz_06_01_jw_transformation_1761480e

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_01_jw_transformation_1761480e',
    category='Cloze',
    front='JW transformation:  cⱼ = ______',
    back='cⱼ = (⊗_{k<j} Zₖ) · (Xⱼ + iYⱼ)/2  ·  Source: docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — VQE Fundamentals',
)
