"""Card: cz_02_08_hydrogen_712a488f

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_hydrogen_712a488f',
    category='Cloze',
    front='Hydrogen:  E_n = ______',
    back='E_n = −13.6 eV/n²  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
