"""Card: cz_01_05_abelian_hsp_07935603

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/05_representation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_05_abelian_hsp_07935603',
    category='Cloze',
    front='Abelian HSP:  H^⊥ = ______',
    back='H^⊥ = {χ : χ|_H = 1}  ·  Source: docs/01_mathematical_foundations/05_representation_theory.md — Representation Theory for Quantum Computing',
)
