"""Card: cz_02_07_photon_statistics_f1ebfb12

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_photon_statistics_f1ebfb12',
    category='Cloze',
    front='Photon statistics:  P(n) = ______',
    back='P(n) = e^{−⟨n⟩}⟨n⟩ⁿ/n!  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
