"""Card: cz_02_10_lindblad_equation_e2f8d700

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_lindblad_equation_e2f8d700',
    category='Cloze',
    front='Lindblad equation:  dρ/dt = ______',
    back='dρ/dt = −i[H,ρ] + Σₖ (Lₖ ρ Lₖ† − ½{Lₖ†Lₖ, ρ})  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
