"""Card: cz_08_05_amplitude_amplification_02c628a5

Generated by tools/gen_cloze.py from docs/08_advanced_topics/05_qsvt.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_05_amplitude_amplification_02c628a5',
    category='Cloze',
    front='Amplitude amplification:  d = ______',
    back='d = O(1/a_min)  ·  Source: docs/08_advanced_topics/05_qsvt.md — Quantum Singular Value Transformation',
)
