"""Card: cz_04_01_uniform_superposition_7c9885ef

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_01_uniform_superposition_7c9885ef',
    category='Cloze',
    front='Uniform superposition:  H^{⊗n}|0⟩^n = ______',
    back='H^{⊗n}|0⟩^n = 1/√(2^n) Σ_{x ∈ {0,1}^n}|x⟩  ·  Source: docs/04_quantum_algorithms/01_quantum_parallelism_and_interference.md — Quantum Parallelism and Interference',
)
