"""Card: cz_06_03_shot_noise_on_gradient_259e882a

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_03_shot_noise_on_gradient_259e882a',
    category='Cloze',
    front='Shot noise on gradient:  Var_S(gᵢ) ≤ ______',
    back='Var_S(gᵢ) ≤ 1/(2S)  ·  Source: docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — The Parameter-Shift Rule and Quantum Gradients',
)
