"""Card: cz_02_10_helstrom_bound_bed743b8

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_helstrom_bound_bed743b8',
    category='Cloze',
    front='Helstrom bound:  p_success = ______',
    back='p_success = ½(1 + D)  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
