"""Card: cz_05_08_displacement_operator_977d4944

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/08_bosonic_codes.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_08_displacement_operator_977d4944',
    category='Cloze',
    front='Displacement operator:  D(β) = ______',
    back='D(β) = e^{β â† - β* â}  ·  Source: docs/05_quantum_error_correction/08_bosonic_codes.md — Bosonic Codes',
)
