"""Card: cz_02_02_qubit_state_bloch_sphere_par_fce0937a

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_02_qubit_state_bloch_sphere_par_fce0937a',
    category='Cloze',
    front='Qubit state (Bloch sphere parameterization):  |ψ⟩ = ______',
    back='|ψ⟩ = cos(θ/2)|0⟩ + e^{iϕ}sin(θ/2)|1⟩  ·  Source: docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — Qubits and the Bloch Sphere',
)
