"""Card: cz_09_02_concentration_2eccbb4b

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/02_quantum_kernels.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_02_concentration_2eccbb4b',
    category='Cloze',
    front='Concentration:  S ≈ ______',
    back='S ≈ 1/(δ² K)  ·  Source: docs/09_quantum_machine_learning/02_quantum_kernels.md — Quantum Kernel Methods',
)
