"""Card: cz_02_05_kraus_representation_69ab3e51

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_05_kraus_representation_69ab3e51',
    category='Cloze',
    front='Kraus representation:  ε(ρ) = ______',
    back='ε(ρ) = Σ_k K_k ρK_k†  ·  Full entry: ε(ρ) = Σ_k K_k ρK_k†,  Σ_k K_k† K_k = I  ·  Source: docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — Density Matrices and Open Systems',
)
