"""Card: cz_02_08_algebra_3b0b2701

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_algebra_3b0b2701',
    category='Cloze',
    front='Algebra:  [Ĵᵢ, Ĵⱼ] = ______',
    back='[Ĵᵢ, Ĵⱼ] = iℏ ε_{ijk} Ĵₖ  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
