"""Card: cz_03_02_swap_from_cnot_456d779a

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_02_swap_from_cnot_456d779a',
    category='Cloze',
    front='SWAP from CNOT:  SWAP = ______',
    back='SWAP = CNOT_{12}·CNOT_{21}·CNOT_{12}  ·  Source: docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — Multi-Qubit Gates',
)
