"""Card: cz_05_05_css_commutativity_75076498

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/05_css_codes_and_steane.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_05_css_commutativity_75076498',
    category='Cloze',
    front='CSS commutativity:  G₂ H₁ᵀ = ______',
    back='G₂ H₁ᵀ = 0  ·  Source: docs/05_quantum_error_correction/05_css_codes_and_steane.md — CSS Codes and the Steane [[7,1,3]] Code',
)
