"""Card: cz_07_03_boson_sampling_probability_ace25b3a

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/03_photonic_and_other_platforms.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_03_boson_sampling_probability_ace25b3a',
    category='Cloze',
    front='Boson sampling probability:  P(s|r) = ______',
    back='P(s|r) = |Perm(U_{rs})|² / (r!s!)  ·  Source: docs/07_quantum_hardware/03_photonic_and_other_platforms.md — Photonic and Other Quantum Computing Platforms',
)
