"""Card: cz_02_10_coherence_times_18948d1d

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_coherence_times_18948d1d',
    category='Cloze',
    front='Coherence times:  1/T₂ = ______',
    back='1/T₂ = 1/(2T₁) + 1/T_φ  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
