"""Card: cz_04_05_diffusion_operator_c6490b66

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/05_grover_search.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_05_diffusion_operator_c6490b66',
    category='Cloze',
    front='Diffusion operator:  G_D = ______',
    back="G_D = H^{⊗n}(2|0⟩⟨0| - I)H^{⊗n}  ·  Source: docs/04_quantum_algorithms/05_grover_search.md — Grover's Search Algorithm",
)
