"""Card: cz_03_02_cnot_action_9711c810

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_02_cnot_action_9711c810',
    category='Cloze',
    front='CNOT action:  CNOT|c,t⟩ = ______',
    back='CNOT|c,t⟩ = |c, c⊕t⟩  ·  Source: docs/03_quantum_gates_and_circuits/02_multi_qubit_gates.md — Multi-Qubit Gates',
)
