"""Card: cz_02_10_bloch_solutions_3f4e1e53

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_bloch_solutions_3f4e1e53',
    category='Cloze',
    front='Bloch solutions:  r_{x,y}(t) = ______',
    back='r_{x,y}(t) = r_{x,y}(0)e^{−t/T₂}  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
