"""Card: cz_04_05_initial_angle_70f7a0ca

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/05_grover_search.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_05_initial_angle_70f7a0ca',
    category='Cloze',
    front='Initial angle:  sinθ = ______',
    back="sinθ = √(M/N)  ·  Full entry: sinθ = √(M/N),  θ ≈ √(M/N) for small M/N  ·  Source: docs/04_quantum_algorithms/05_grover_search.md — Grover's Search Algorithm",
)
