"""Card: cz_06_05_barren_plateau_theorem_globa_46dda437

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/05_barren_plateaus.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_05_barren_plateau_theorem_globa_46dda437',
    category='Cloze',
    front='Barren plateau theorem (global cost):  Var_θ[∂C/∂θᵢ] ≤ ______',
    back='Var_θ[∂C/∂θᵢ] ≤ 2/4^n  ·  Source: docs/06_variational_quantum_algorithms/05_barren_plateaus.md — Barren Plateaus',
)
