"""Card: cz_01_09_bures_distance_mixed_states_5af2ede6

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/09_topology_and_geometry.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_09_bures_distance_mixed_states_5af2ede6',
    category='Cloze',
    front='Bures distance (mixed states):  d_B(ρ,σ)² = ______',
    back='d_B(ρ,σ)² = 2(1 - √F(ρ,σ))  ·  Source: docs/01_mathematical_foundations/09_topology_and_geometry.md — Topology and Geometry for Quantum Computing',
)
