"""Card: cz_01_05_sum_of_squares_ac4dea44

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/05_representation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_05_sum_of_squares_ac4dea44',
    category='Cloze',
    front='Sum of squares:  Σ_i d_i² = ______',
    back='Σ_i d_i² = |G|  ·  Source: docs/01_mathematical_foundations/05_representation_theory.md — Representation Theory for Quantum Computing',
)
