"""Card: cz_09_04_encoding_cost_measured_6d0b91f1

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/04_qml_in_practice.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_04_encoding_cost_measured_6d0b91f1',
    category='Cloze',
    front='Encoding cost (measured):  CNOT = ______',
    back='CNOT = 2ⁿ - n - 1  ·  Source: docs/09_quantum_machine_learning/04_qml_in_practice.md — QML in Practice: Claims, Evidence and Benchmarks',
)
