"""Card: cz_04_09_coined_walk_step_c8650448

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/09_quantum_walks.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_09_coined_walk_step_c8650448',
    category='Cloze',
    front='Coined walk step:  U = ______',
    back='U = S(I⊗H)  ·  Full entry: U = S(I⊗H),  S|x⟩|0⟩ = |x+1⟩|0⟩,  S|x⟩|1⟩ = |x-1⟩|1⟩  ·  Source: docs/04_quantum_algorithms/09_quantum_walks.md — Quantum Walks',
)
