"""Card: cz_05_02_syndrome_b566733f

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/02_classical_error_correction.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_02_syndrome_b566733f',
    category='Cloze',
    front='Syndrome:  s = ______',
    back='s = H eᵀ  ·  Source: docs/05_quantum_error_correction/02_classical_error_correction.md — Classical Error Correction',
)
