"""Card: cz_02_04_classical_bound_cc2c43a2

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_04_classical_bound_cc2c43a2',
    category='Cloze',
    front='Classical bound:  |⟨S⟩| ≤ ______',
    back='|⟨S⟩| ≤ 2  ·  Source: docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — Entanglement and Nonlocality',
)
