"""Card: cz_01_02_euler_s_formula_3a57d8f9

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_02_euler_s_formula_3a57d8f9',
    category='Cloze',
    front="Euler's formula:  e^{iθ} = ______",
    back='e^{iθ} = cosθ + i sinθ  ·  Source: docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — Complex Numbers and Hilbert Spaces',
)
