"""Card: cz_08_03_qubitization_cost_6ca5392b

Generated by tools/gen_cloze.py from docs/08_advanced_topics/03_many_body_physics_and_simulation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_03_qubitization_cost_6ca5392b',
    category='Cloze',
    front='Qubitization cost:  ||H||_1 = ______',
    back='||H||_1 = Σ |cⱼ|  ·  Source: docs/08_advanced_topics/03_many_body_physics_and_simulation.md — Many-Body Physics and Quantum Simulation',
)
