"""Card: cz_06_04_mixer_unitary_b005974e

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/04_qaoa.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_04_mixer_unitary_b005974e',
    category='Cloze',
    front='Mixer unitary:  U_M(β) = ______',
    back='U_M(β) = ⊗ᵢ e^{-iβXᵢ} = ⊗ᵢ Rx(2β)  ·  Source: docs/06_variational_quantum_algorithms/04_qaoa.md — QAOA: Quantum Approximate Optimization Algorithm',
)
