"""Card: cz_04_06_eigenvalues_of_u_a_934fe156

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/06_shors_algorithm.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_06_eigenvalues_of_u_a_934fe156',
    category='Cloze',
    front='Eigenvalues of U_a:  |u_s⟩ = ______',
    back="|u_s⟩ = 1/√r Σ_{j=0}^{r-1}e^{-2πisj/r}|a^j mod N⟩  ·  Full entry: U_a|u_s⟩ = e^{2πis/r}|u_s⟩,  |u_s⟩ = 1/√r Σ_{j=0}^{r-1}e^{-2πisj/r}|a^j mod N⟩  ·  Source: docs/04_quantum_algorithms/06_shors_algorithm.md — Shor's Algorithm",
)
