"""Card: cz_08_03_jw_mapping_1bb19317

Generated by tools/gen_cloze.py from docs/08_advanced_topics/03_many_body_physics_and_simulation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_03_jw_mapping_1bb19317',
    category='Cloze',
    front='JW mapping:  cⱼ = ______',
    back='cⱼ = (⊗_{k<j} Zₖ) ⊗ (Xⱼ+iYⱼ)/2  ·  Source: docs/08_advanced_topics/03_many_body_physics_and_simulation.md — Many-Body Physics and Quantum Simulation',
)
