"""Card: cz_08_01_grover_ad73b160

Generated by tools/gen_cloze.py from docs/08_advanced_topics/01_quantum_complexity_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_01_grover_ad73b160',
    category='Cloze',
    front='Grover:  Q(search) = ______',
    back='Q(search) = O(√N)  ·  Source: docs/08_advanced_topics/01_quantum_complexity_theory.md — Quantum Complexity Theory',
)
