"""Card: cz_06_04_qaoa_circuit_3252f4ee

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/04_qaoa.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_04_qaoa_circuit_3252f4ee',
    category='Cloze',
    front='QAOA circuit:  |ψ(γ,β)⟩ = ______',
    back='|ψ(γ,β)⟩ = ∏_{l=p}^1 [e^{-iβₗΣXᵢ} e^{-iγₗH_C}] |+⟩^⊗n  ·  Source: docs/06_variational_quantum_algorithms/04_qaoa.md — QAOA: Quantum Approximate Optimization Algorithm',
)
