"""Card: cz_01_02_cauchy_schwarz_inequality_f984c519

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_02_cauchy_schwarz_inequality_f984c519',
    category='Cloze',
    front='Cauchy-Schwarz inequality:  |⟨ϕ|ψ⟩|^2 ≤ ______',
    back='|⟨ϕ|ψ⟩|^2 ≤ ⟨ϕ|ϕ⟩ ⟨ψ|ψ⟩  ·  Source: docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — Complex Numbers and Hilbert Spaces',
)
