"""Card: cz_03_05_byproduct_propagation_feed_f_cb0ecab8

Generated by tools/gen_cloze.py from docs/03_quantum_gates_and_circuits/05_measurement_based_qc.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_03_05_byproduct_propagation_feed_f_cb0ecab8',
    category='Cloze',
    front='Byproduct propagation (feed-forward rule):  X R_z(θ) = ______',
    back='X R_z(θ) = R_z(-θ) X  (up to phase)  ·  Full entry: X R_z(θ) = R_z(-θ) X (up to phase),  H X = Z H,  HZ = XH  ·  Source: docs/03_quantum_gates_and_circuits/05_measurement_based_qc.md — Measurement-Based Quantum Computation',
)
