"""Card: cz_02_08_spectrum_2a735aa5

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_spectrum_2a735aa5',
    category='Cloze',
    front='Spectrum:  Ĵ²|j,m⟩ = ______',
    back='Ĵ²|j,m⟩ = ℏ²j(j+1)|j,m⟩  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
