"""Card: cz_06_07_grape_gradient_9cc09ef3

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_07_grape_gradient_9cc09ef3',
    category='Cloze',
    front='GRAPE gradient:  ∂F/∂u_{k,j} = ______',
    back='∂F/∂u_{k,j} = 2Δt · Re[⟨Λⱼ|(-iHₖ)|Pⱼ⟩]  ·  Source: docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — Quantum Optimal Control',
)
