"""Card: cz_09_01_zz_feature_map_phases_13fd6f27

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/01_data_encoding.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_01_zz_feature_map_phases_13fd6f27',
    category='Cloze',
    front='ZZ feature map phases:  φ_i(x) = ______',
    back='φ_i(x) = 2x_i  ·  Source: docs/09_quantum_machine_learning/01_data_encoding.md — Data Encoding and Quantum Feature Maps',
)
