"""Card: cz_01_06_hoeffding_and_the_shot_count_98e6d442

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_hoeffding_and_the_shot_count_98e6d442',
    category='Cloze',
    front='Hoeffding and the shot-count rule (Xᵢ ∈ [a,b]):  N ≥ ______',
    back='N ≥ (b−a)² ln(2/δ)/(2ε²)  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
