"""Card: cz_06_06_noise_decay_with_depth_noise_49be3b1f

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_06_noise_decay_with_depth_noise_49be3b1f',
    category='Cloze',
    front='Noise decay with depth (noise-induced BP):  |C(θ)-C_mix| ≤ ______',
    back='|C(θ)-C_mix| ≤ (1-p)^D ‖O‖  ·  Source: docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — Noise and Error Mitigation in NISQ Algorithms',
)
