"""Card: cz_04_09_walk_search_cost_template_f9713461

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/09_quantum_walks.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_09_walk_search_cost_template_f9713461',
    category='Cloze',
    front='Walk-search cost template:  Q = ______',
    back='Q = Setup + 1/√ε(1/√δ·Update + Check)  ·  Source: docs/04_quantum_algorithms/09_quantum_walks.md — Quantum Walks',
)
