"""Card: cz_05_03_shor_code_word_d3369970

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/03_repetition_code.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_03_shor_code_word_d3369970',
    category='Cloze',
    front='Shor code word:  |0_L⟩ = ______',
    back='|0_L⟩ = [(|000⟩+|111⟩)^⊗3] / 2√2  ·  Source: docs/05_quantum_error_correction/03_repetition_code.md — The Quantum Repetition Code',
)
