"""Card: cz_06_07_margolus_levitin_qsl_63295985

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_07_margolus_levitin_qsl_63295985',
    category='Cloze',
    front='Margolus-Levitin QSL:  τ ≥ ______',
    back='τ ≥ πℏ / (2⟨E-E₀⟩)  ·  Source: docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — Quantum Optimal Control',
)
