"""Card: cz_02_08_spin_1_2_0a1a966e

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_spin_1_2_0a1a966e',
    category='Cloze',
    front='Spin-½:  Ŝ = ______',
    back='Ŝ = (ℏ/2)σ  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
