"""Card: cz_05_07_solovay_kitaev_257d15cf

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/07_fault_tolerance.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_07_solovay_kitaev_257d15cf',
    category='Cloze',
    front='Solovay-Kitaev:  c ≈ ______',
    back='c ≈ 3.97  ·  Source: docs/05_quantum_error_correction/07_fault_tolerance.md — Fault-Tolerant Quantum Computation',
)
