"""Card: cz_02_07_ground_state_length_scale_bd62888d

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_ground_state_length_scale_bd62888d',
    category='Cloze',
    front='Ground-state length scale:  x₀ = ______',
    back='x₀ = √(ℏ/mω)  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
