"""Card: cz_02_03_heisenberg_position_momentum_0a5242e8

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/03_quantum_measurements.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_03_heisenberg_position_momentum_0a5242e8',
    category='Cloze',
    front='Heisenberg (position-momentum):  ΔX · ΔP ≥ ______',
    back='ΔX · ΔP ≥ ℏ/2  ·  Source: docs/02_quantum_mechanics/03_quantum_measurements.md — Quantum Measurements',
)
