"""Card: cz_01_07_shift_diagonalization_eb8ca674

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_07_shift_diagonalization_eb8ca674',
    category='Cloze',
    front='Shift diagonalization:  F S F† = ______',
    back='F S F† = diag(ωᵏ)  ·  Source: docs/01_mathematical_foundations/07_number_theory_and_fourier_analysis.md — Number Theory and Fourier Analysis',
)
