"""Card: cz_05_06_logical_error_rate_17f4703b

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/06_surface_code.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_06_logical_error_rate_17f4703b',
    category='Cloze',
    front='Logical error rate:  p_L ≈ ______',
    back='p_L ≈ C(p/p_th)^{⌈d/2⌉}  ·  Source: docs/05_quantum_error_correction/06_surface_code.md — The Surface Code',
)
