"""Card: cz_01_09_su_2_so_3_double_cover_ca2114c9

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/09_topology_and_geometry.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_09_su_2_so_3_double_cover_ca2114c9',
    category='Cloze',
    front='SU(2) → SO(3) double cover:  Φ(U)ᵢⱼ = ______',
    back='Φ(U)ᵢⱼ = ½ Tr(σᵢ U σⱼ U†)  ·  Source: docs/01_mathematical_foundations/09_topology_and_geometry.md — Topology and Geometry for Quantum Computing',
)
