"""Card: cz_02_07_displacement_159409b8

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/07_harmonic_oscillator.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_07_displacement_159409b8',
    category='Cloze',
    front='Displacement:  D̂(α) = ______',
    back='D̂(α) = e^{αâ†−α*â}  ·  Source: docs/02_quantum_mechanics/07_harmonic_oscillator.md — The Quantum Harmonic Oscillator',
)
