"""Card: cz_04_07_controlled_rotation_ba7162ab

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/07_hhl_quantum_linear_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_07_controlled_rotation_ba7162ab',
    category='Cloze',
    front='Controlled rotation:  C ≤ ______',
    back='C ≤ λ̃_{min}  ·  Full entry: |λ̃⟩|0⟩ → |λ̃⟩(√(1 - C^2/λ̃^2) |0⟩ + (C/λ̃)|1⟩),  C ≤ λ̃_{min}  ·  Source: docs/04_quantum_algorithms/07_hhl_quantum_linear_systems.md — HHL and Quantum Linear Systems',
)
