"""Card: cz_04_07_post_selection_probability_ba00e258

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/07_hhl_quantum_linear_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_07_post_selection_probability_ba00e258',
    category='Cloze',
    front='Post-selection probability:  P(1) = ______',
    back='P(1) = Σ_j |β_j|^2 C^2/λ̃_j^2 = Ω(1/κ^2)  ·  Source: docs/04_quantum_algorithms/07_hhl_quantum_linear_systems.md — HHL and Quantum Linear Systems',
)
