"""Card: cz_06_01_pauli_decomposition_59764dd8

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_01_pauli_decomposition_59764dd8',
    category='Cloze',
    front='Pauli decomposition:  H = ______',
    back='H = Σ_P c_P P  ·  Source: docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — VQE Fundamentals',
)
