"""Card: cz_01_08_residue_theorem_c701313c

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_08_residue_theorem_c701313c',
    category='Cloze',
    front='Residue theorem:  ∮_C f(z) dz = ______',
    back='∮_C f(z) dz = 2πi Σⱼ Res(f, zⱼ)  ·  Source: docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — Analysis for Quantum Mechanics',
)
