"""Card: cz_02_04_bell_state_creation_79660330

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_04_bell_state_creation_79660330',
    category='Cloze',
    front='Bell state creation:  |Φ^+⟩ = ______',
    back='|Φ^+⟩ = CNOT_{12} · (H ⊗ I)|00⟩  ·  Source: docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — Entanglement and Nonlocality',
)
