"""Card: cz_07_01_anharmonicity_e3045a8b

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/01_superconducting_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_01_anharmonicity_e3045a8b',
    category='Cloze',
    front='Anharmonicity:  α ≈ ______',
    back='α ≈ -E_C / ℏ  ·  Source: docs/07_quantum_hardware/01_superconducting_qubits.md — Superconducting Qubits',
)
