"""Card: cz_02_06_tunneling_765538e5

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_tunneling_765538e5',
    category='Cloze',
    front='Tunneling:  T = ______',
    back='T = [1 + V₀² sinh²(κa)/(4E(V₀−E))]^{−1}  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
