"""Card: cz_05_02_error_correction_capacity_245b3278

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/02_classical_error_correction.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_02_error_correction_capacity_245b3278',
    category='Cloze',
    front='Error correction capacity:  t = ______',
    back='t = ⌊(d-1)/2⌋  ·  Source: docs/05_quantum_error_correction/02_classical_error_correction.md — Classical Error Correction',
)
