"""Card: cz_05_05_steane_code_01d3291a

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/05_css_codes_and_steane.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_05_steane_code_01d3291a',
    category='Cloze',
    front='Steane code:  C₁ = ______',
    back='C₁ = [7,4,3]  ·  Source: docs/05_quantum_error_correction/05_css_codes_and_steane.md — CSS Codes and the Steane [[7,1,3]] Code',
)
