"""Card: cz_09_01_re_uploading_spectrum_03d0b6ce

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/01_data_encoding.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_01_re_uploading_spectrum_03d0b6ce',
    category='Cloze',
    front='Re-uploading spectrum:  f(x, θ) = ______',
    back='f(x, θ) = Σ_{ω ∈ Ω} c_ω(θ)e^{iωx}  ·  Source: docs/09_quantum_machine_learning/01_data_encoding.md — Data Encoding and Quantum Feature Maps',
)
