"""Card: cz_02_01_postulate_2_unitary_evolutio_b49ebaa4

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_01_postulate_2_unitary_evolutio_b49ebaa4',
    category='Cloze',
    front='Postulate 2 — Unitary evolution:  |ψ(t)⟩ = ______',
    back='|ψ(t)⟩ = e^{-iHt/ℏ}|ψ(0)⟩  ·  Full entry: |ψ(t)⟩ = e^{-iHt/ℏ}|ψ(0)⟩,  U† U = I  ·  Source: docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — Postulates of Quantum Mechanics',
)
