"""Card: cz_02_06_tdse_fdeae28d

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_tdse_fdeae28d',
    category='Cloze',
    front='TDSE:  iℏ ∂ψ/∂t = ______',
    back='iℏ ∂ψ/∂t = −(ℏ²/2m)∂²ψ/∂x² + V(x)ψ  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
