"""Card: cz_01_08_roots_of_unity_orthogonality_f569b6a6

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_08_roots_of_unity_orthogonality_f569b6a6',
    category='Cloze',
    front='Roots of unity orthogonality:  Σ_{k=0}^{N-1} e^{2πijk/N} = ______',
    back='Σ_{k=0}^{N-1} e^{2πijk/N} = N δ_{j ≡ 0 (mod N)}  ·  Source: docs/01_mathematical_foundations/08_analysis_for_quantum_mechanics.md — Analysis for Quantum Mechanics',
)
