"""Card: cz_02_06_group_velocity_ce3124d9

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_06_group_velocity_ce3124d9',
    category='Cloze',
    front='Group velocity:  v_g = ______',
    back='v_g = dω/dk = p/m  ·  Source: docs/02_quantum_mechanics/06_wave_mechanics_and_schrodinger.md — Wave Mechanics and the Schrödinger Equation',
)
