"""Card: cz_04_05_oracle_phase_oracle_78a2b4d4

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/05_grover_search.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_05_oracle_phase_oracle_78a2b4d4',
    category='Cloze',
    front='Oracle (phase oracle):  O_f = ______',
    back="O_f = I - 2 Σ_{x: f(x)=1}|x⟩⟨x|  ·  Source: docs/04_quantum_algorithms/05_grover_search.md — Grover's Search Algorithm",
)
