"""Card: cz_01_03_tensor_product_dimension_fdfbb468

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/03_tensor_products_and_multipartite_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_03_tensor_product_dimension_fdfbb468',
    category='Cloze',
    front='Tensor product dimension:  dim(V ⊗ W) = ______',
    back='dim(V ⊗ W) = dim(V) · dim(W)  ·  Source: docs/01_mathematical_foundations/03_tensor_products_and_multipartite_systems.md — Tensor Products and Multipartite Systems',
)
