"""Card: cz_02_03_variance_7645777d

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/03_quantum_measurements.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_03_variance_7645777d',
    category='Cloze',
    front='Variance:  (ΔM)^2 = ______',
    back='(ΔM)^2 = ⟨M^2⟩ - ⟨M⟩^2  ·  Source: docs/02_quantum_mechanics/03_quantum_measurements.md — Quantum Measurements',
)
