"""Card: cz_06_02_adapt_gradient_selection_e4268e91

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/02_ansatz_design.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_02_adapt_gradient_selection_e4268e91',
    category='Cloze',
    front='ADAPT gradient selection:  ∂E/∂θₖ = ______',
    back='∂E/∂θₖ = ⟨ψ|[H, Aₖ]|ψ⟩  ·  Source: docs/06_variational_quantum_algorithms/02_ansatz_design.md — Ansatz Design',
)
