"""Card: cz_01_04_double_cover_0538d968

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_double_cover_0538d968',
    category='Cloze',
    front='Double cover:  e^{-i·2π·n̂·σ/2} = ______',
    back='e^{-i·2π·n̂·σ/2} = -I  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
