"""Card: cz_08_05_chebyshev_response_9f6b5fcf

Generated by tools/gen_cloze.py from docs/08_advanced_topics/05_qsvt.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_05_chebyshev_response_9f6b5fcf',
    category='Cloze',
    front='Chebyshev response:  ⟨0|W(x)^d|0⟩ = ______',
    back='⟨0|W(x)^d|0⟩ = T_d(x) = cos(d arccos x)  ·  Source: docs/08_advanced_topics/05_qsvt.md — Quantum Singular Value Transformation',
)
