"""Card: cz_05_01_pauli_decomposition_of_any_s_f6444909

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/01_why_qec_is_hard.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_01_pauli_decomposition_of_any_s_f6444909',
    category='Cloze',
    front='Pauli decomposition of any single-qubit operator:  E = ______',
    back='E = e_I I + e_X X + e_Y Y + e_Z Z  ·  Source: docs/05_quantum_error_correction/01_why_qec_is_hard.md — Why Quantum Error Correction Is Hard',
)
