"""Card: cz_02_02_rotation_operator_dfd6a3c4

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_02_rotation_operator_dfd6a3c4',
    category='Cloze',
    front='Rotation operator:  R_{n̂}(θ) = ______',
    back='R_{n̂}(θ) = e^{-iθn̂·σ/2} = cos(θ/2)I - i sin(θ/2)(n̂·σ)  ·  Source: docs/02_quantum_mechanics/02_qubits_and_the_bloch_sphere.md — Qubits and the Bloch Sphere',
)
