"""Card: cz_05_06_threshold_bdf8fcb2

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/06_surface_code.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_06_threshold_bdf8fcb2',
    category='Cloze',
    front='Threshold:  p_th ≈ ______',
    back='p_th ≈ 1%  ·  Source: docs/05_quantum_error_correction/06_surface_code.md — The Surface Code',
)
