"""Card: cz_02_05_density_matrix_of_mixed_stat_75c552b2

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_05_density_matrix_of_mixed_stat_75c552b2',
    category='Cloze',
    front='Density matrix of mixed state:  ρ = ______',
    back='ρ = Σ_i p_i|ψ_i⟩⟨ψ_i|  ·  Full entry: ρ = Σ_i p_i|ψ_i⟩⟨ψ_i|,  p_i ≥ 0,  Σ_i p_i = 1  ·  Source: docs/02_quantum_mechanics/05_density_matrices_and_open_systems.md — Density Matrices and Open Systems',
)
