"""Card: cz_01_05_orthogonality_and_multiplici_46b75540

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/05_representation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_05_orthogonality_and_multiplici_46b75540',
    category='Cloze',
    front='Orthogonality and multiplicities:  ⟨χ_i, χ_j⟩ = ______',
    back='⟨χ_i, χ_j⟩ = δ_ij  ·  Source: docs/01_mathematical_foundations/05_representation_theory.md — Representation Theory for Quantum Computing',
)
