"""Card: cz_06_07_drag_correction_526193e4

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_07_drag_correction_526193e4',
    category='Cloze',
    front='DRAG correction:  Ω_X(t) = ______',
    back='Ω_X(t) = Ω₀(t)  ·  Source: docs/06_variational_quantum_algorithms/07_quantum_optimal_control.md — Quantum Optimal Control',
)
