"""Card: cz_02_09_fermi_s_golden_rule_ffd41feb

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/09_perturbation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_09_fermi_s_golden_rule_ffd41feb',
    category='Cloze',
    front="Fermi's golden rule:  Γ = ______",
    back='Γ = (2π/ℏ)|⟨f|V̂|i⟩|² ρ(E_f)  ·  Source: docs/02_quantum_mechanics/09_perturbation_theory.md — Perturbation Theory and Driven Systems',
)
