"""Card: cz_08_04_ising_braiding_phases_nayak_2b7485cc

Generated by tools/gen_cloze.py from docs/08_advanced_topics/04_topological_quantum_computation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_04_ising_braiding_phases_nayak_2b7485cc',
    category='Cloze',
    front='Ising braiding phases (Nayak et al. RMP 2008 convention):  R₁^{σσ} = ______',
    back='R₁^{σσ} = e^{-iπ/8}  ·  Source: docs/08_advanced_topics/04_topological_quantum_computation.md — Topological Quantum Computation',
)
