"""Card: cz_02_09_second_order_c721a9ac

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/09_perturbation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_09_second_order_c721a9ac',
    category='Cloze',
    front='Second order:  E_n² = ______',
    back='E_n² = Σ_{m≠n} |⟨m⁰|V̂|n⁰⟩|²/(E_n⁰−E_m⁰)  ·  Source: docs/02_quantum_mechanics/09_perturbation_theory.md — Perturbation Theory and Driven Systems',
)
