"""Card: cz_02_01_postulate_1_normalization_000dab54

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_01_postulate_1_normalization_000dab54',
    category='Cloze',
    front='Postulate 1 — Normalization:  ⟨ψ|ψ⟩ = ______',
    back='⟨ψ|ψ⟩ = 1  ·  Source: docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — Postulates of Quantum Mechanics',
)
