"""Card: cz_06_06_zne_linear_extrapolation_3e59002d

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_06_zne_linear_extrapolation_3e59002d',
    category='Cloze',
    front='ZNE (linear extrapolation):  C(0) ≈ ______',
    back='C(0) ≈ [c₂C(c₁λ) - c₁C(c₂λ)] / (c₂-c₁)  ·  Source: docs/06_variational_quantum_algorithms/06_noise_and_error_mitigation.md — Noise and Error Mitigation in NISQ Algorithms',
)
