"""Card: cz_06_04_cost_hamiltonian_maxcut_5c6c0d07

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/04_qaoa.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_04_cost_hamiltonian_maxcut_5c6c0d07',
    category='Cloze',
    front='Cost Hamiltonian (MaxCut):  H_C = ______',
    back='H_C = (1/2) Σ_{(i,j)∈E} (I - ZᵢZⱼ)  ·  Source: docs/06_variational_quantum_algorithms/04_qaoa.md — QAOA: Quantum Approximate Optimization Algorithm',
)
