"""Card: cz_02_10_uhlmann_e314f135

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_10_uhlmann_e314f135',
    category='Cloze',
    front='Uhlmann:  F(ρ,σ) = ______',
    back='F(ρ,σ) = max |⟨ψ_ρ|ψ_σ⟩|²  ·  Source: docs/02_quantum_mechanics/10_distance_measures_and_lindblad.md — Distance Measures and the Lindblad Master Equation',
)
