"""Card: cz_09_02_compute_uncompute_estimator_9b455ff3

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/02_quantum_kernels.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_02_compute_uncompute_estimator_9b455ff3',
    category='Cloze',
    front='Compute–uncompute estimator:  Var = ______',
    back='Var = K(1-K)/S  ·  Source: docs/09_quantum_machine_learning/02_quantum_kernels.md — Quantum Kernel Methods',
)
