"""Card: cz_05_07_gate_teleportation_t_gate_eed7cf43

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/07_fault_tolerance.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_07_gate_teleportation_t_gate_eed7cf43',
    category='Cloze',
    front='Gate teleportation T gate:  |T⟩ = ______',
    back='|T⟩ = T|+⟩  ·  Source: docs/05_quantum_error_correction/07_fault_tolerance.md — Fault-Tolerant Quantum Computation',
)
