"""Card: cz_04_08_bb84_signal_states_6c945e48

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/08_quantum_cryptography.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_08_bb84_signal_states_6c945e48',
    category='Cloze',
    front='BB84 signal states:  |⟨0|+⟩|² = ______',
    back='|⟨0|+⟩|² = 1/2  ·  Source: docs/04_quantum_algorithms/08_quantum_cryptography.md — Quantum Cryptography',
)
