"""Card: cz_02_09_rabi_frequency_f2e3aaba

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/09_perturbation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_09_rabi_frequency_f2e3aaba',
    category='Cloze',
    front='Rabi frequency:  Ω_R = ______',
    back='Ω_R = √(Ω² + Δ²)  ·  Source: docs/02_quantum_mechanics/09_perturbation_theory.md — Perturbation Theory and Driven Systems',
)
