"""Card: cz_04_06_superposition_of_eigenstates_2393edfc

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/06_shors_algorithm.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_06_superposition_of_eigenstates_2393edfc',
    category='Cloze',
    front='Superposition of eigenstates:  |1⟩ = ______',
    back="|1⟩ = 1/√r Σ_{s=0}^{r-1}|u_s⟩  ·  Source: docs/04_quantum_algorithms/06_shors_algorithm.md — Shor's Algorithm",
)
