"""Card: cz_06_03_parameter_shift_rule_67d2ef4f

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_03_parameter_shift_rule_67d2ef4f',
    category='Cloze',
    front='Parameter-shift rule:  ∂f/∂θᵢ = ______',
    back='∂f/∂θᵢ = [f(θ + π/2 eᵢ) - f(θ - π/2 eᵢ)] / 2  ·  Source: docs/06_variational_quantum_algorithms/03_parameter_shift_gradient.md — The Parameter-Shift Rule and Quantum Gradients',
)
