"""Card: cz_05_07_surface_code_logical_rate_e991dcbd

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/07_fault_tolerance.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_07_surface_code_logical_rate_e991dcbd',
    category='Cloze',
    front='Surface code logical rate:  p_L ≈ ______',
    back='p_L ≈ A(p/p_th)^{⌈d/2⌉}  ·  Source: docs/05_quantum_error_correction/07_fault_tolerance.md — Fault-Tolerant Quantum Computation',
)
