"""Card: cz_02_01_postulate_3_born_rule_genera_4d7ee1aa

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_01_postulate_3_born_rule_genera_4d7ee1aa',
    category='Cloze',
    front='Postulate 3 — Born rule (general):  p(m) = ______',
    back='p(m) = ⟨ψ|M_m† M_m|ψ⟩  ·  Source: docs/02_quantum_mechanics/01_postulates_of_quantum_mechanics.md — Postulates of Quantum Mechanics',
)
