"""Card: cz_08_04_kitaev_chain_mzms_c4c81633

Generated by tools/gen_cloze.py from docs/08_advanced_topics/04_topological_quantum_computation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_04_kitaev_chain_mzms_c4c81633',
    category='Cloze',
    front='Kitaev chain MZMs:  [H, γ₁] = ______',
    back='[H, γ₁] = [H, γ_{2N}] = 0  ·  Source: docs/08_advanced_topics/04_topological_quantum_computation.md — Topological Quantum Computation',
)
