"""Card: cz_02_04_schmidt_decomposition_797e3f1c

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_04_schmidt_decomposition_797e3f1c',
    category='Cloze',
    front='Schmidt decomposition:  |ψ_{AB}⟩ = ______',
    back='|ψ_{AB}⟩ = Σ_{i=1}^r λ_i |i_A⟩|i_B⟩  ·  Full entry: |ψ_{AB}⟩ = Σ_{i=1}^r λ_i |i_A⟩|i_B⟩,  λ_i > 0,  Σ_i λ_i^2 = 1  ·  Source: docs/02_quantum_mechanics/04_entanglement_and_nonlocality.md — Entanglement and Nonlocality',
)
