"""Card: cz_01_02_polar_form_f0b25bd0

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_02_polar_form_f0b25bd0',
    category='Cloze',
    front='Polar form:  z = ______',
    back='z = |z|e^{i arg(z)}  ·  Full entry: z = |z|e^{i arg(z)},  |z|^2 = zz^*  ·  Source: docs/01_mathematical_foundations/02_complex_numbers_and_hilbert_spaces.md — Complex Numbers and Hilbert Spaces',
)
