"""Card: cz_01_06_distinguishing_p_from_q_786c9fae

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/06_probability_and_statistics.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_06_distinguishing_p_from_q_786c9fae',
    category='Cloze',
    front='Distinguishing p from q:  N ≥ ______',
    back='N ≥ 2 ln(1/δ)/(q − p)²  ·  Source: docs/01_mathematical_foundations/06_probability_and_statistics.md — Probability and Statistics for Quantum Computing',
)
