"""Card: cz_09_03_parameter_shift_4c025c6e

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/03_variational_classifiers.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_03_parameter_shift_4c025c6e',
    category='Cloze',
    front='Parameter shift:  ∂f/∂θ_k = ______',
    back='∂f/∂θ_k = [f(θ + (π/2)e_k) - f(θ - (π/2)e_k)]/2  ·  Source: docs/09_quantum_machine_learning/03_variational_classifiers.md — Variational Quantum Classifiers',
)
