"""Card: cz_09_01_angle_encoding_kernel_2679de18

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/01_data_encoding.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_01_angle_encoding_kernel_2679de18',
    category='Cloze',
    front="Angle encoding kernel:  K(x, x') = ______",
    back="K(x, x') = ∏_i cos²((x_i - x'_i)/2)  ·  Source: docs/09_quantum_machine_learning/01_data_encoding.md — Data Encoding and Quantum Feature Maps",
)
