"""Card: cz_09_02_projected_kernel_17f4673c

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/02_quantum_kernels.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_02_projected_kernel_17f4673c',
    category='Cloze',
    front="Projected kernel:  K_PQ(x,x') = ______",
    back="K_PQ(x,x') = exp(-γ Σ_k ‖ρ_k(x) - ρ_k(x')‖²_F)  ·  Source: docs/09_quantum_machine_learning/02_quantum_kernels.md — Quantum Kernel Methods",
)
