"""Card: cz_08_04_ising_fusion_c0b0f4c7

Generated by tools/gen_cloze.py from docs/08_advanced_topics/04_topological_quantum_computation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_04_ising_fusion_c0b0f4c7',
    category='Cloze',
    front='Ising fusion:  σ × σ = ______',
    back='σ × σ = 1 + ψ  ·  Source: docs/08_advanced_topics/04_topological_quantum_computation.md — Topological Quantum Computation',
)
