"""Card: cz_02_09_first_order_amplitude_705f0d5c

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/09_perturbation_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_09_first_order_amplitude_705f0d5c',
    category='Cloze',
    front='First-order amplitude:  c_f(t) = ______',
    back="c_f(t) = (1/iℏ) ∫₀^t dt' ⟨f|V̂(t')|i⟩ e^{iω_{fi}t'}  ·  Source: docs/02_quantum_mechanics/09_perturbation_theory.md — Perturbation Theory and Driven Systems",
)
