"""Card: cz_05_05_css_inclusion_condition_2a18e34b

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/05_css_codes_and_steane.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_05_css_inclusion_condition_2a18e34b',
    category='Cloze',
    front='CSS inclusion condition:  H₁ Gᵀ₂ = ______',
    back='H₁ Gᵀ₂ = 0  ·  Source: docs/05_quantum_error_correction/05_css_codes_and_steane.md — CSS Codes and the Steane [[7,1,3]] Code',
)
