"""Card: cz_01_03_n_qubit_hilbert_space_f14a478c

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/03_tensor_products_and_multipartite_systems.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_03_n_qubit_hilbert_space_f14a478c',
    category='Cloze',
    front='n-qubit Hilbert space:  (ℂ^2)^{⊗n} = ______',
    back='(ℂ^2)^{⊗n} = ℂ^{2^n}  ·  Source: docs/01_mathematical_foundations/03_tensor_products_and_multipartite_systems.md — Tensor Products and Multipartite Systems',
)
