"""Card: cz_09_03_vqc_model_3a8ba86c

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/03_variational_classifiers.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_03_vqc_model_3a8ba86c',
    category='Cloze',
    front='VQC model:  f(x, θ) = ______',
    back='f(x, θ) = ⟨0|U_φ(x)† W(θ)† O W(θ) U_φ(x)|0⟩ = Tr[ρ(x) M(θ)]  ·  Source: docs/09_quantum_machine_learning/03_variational_classifiers.md — Variational Quantum Classifiers',
)
