"""Card: cz_08_01_collision_650cb788

Generated by tools/gen_cloze.py from docs/08_advanced_topics/01_quantum_complexity_theory.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_01_collision_650cb788',
    category='Cloze',
    front='Collision:  Q(collision) = ______',
    back='Q(collision) = Θ(N^{1/3})  ·  Source: docs/08_advanced_topics/01_quantum_complexity_theory.md — Quantum Complexity Theory',
)
