"""Card: cz_06_01_uccsd_ansatz_9a92ba9c

Generated by tools/gen_cloze.py from docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_06_01_uccsd_ansatz_9a92ba9c',
    category='Cloze',
    front='UCCSD ansatz:  |ψ(θ)⟩ = ______',
    back='|ψ(θ)⟩ = exp(T(θ) - T†(θ))|ψ_ref⟩  ·  Source: docs/06_variational_quantum_algorithms/01_vqe_fundamentals.md — VQE Fundamentals',
)
