"""Card: cz_02_08_two_qubits_32463e3a

Generated by tools/gen_cloze.py from docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_02_08_two_qubits_32463e3a',
    category='Cloze',
    front='Two qubits:  ½ ⊗ ½ = ______',
    back='½ ⊗ ½ = 1 ⊕ 0  ·  Source: docs/02_quantum_mechanics/08_angular_momentum_and_hydrogen.md — Angular Momentum and the Hydrogen Atom',
)
