"""Card: cz_05_02_self_orthogonality_ac67b6be

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/02_classical_error_correction.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_02_self_orthogonality_ac67b6be',
    category='Cloze',
    front='Self-orthogonality:  G Gᵀ = ______',
    back='G Gᵀ = 0  ·  Source: docs/05_quantum_error_correction/02_classical_error_correction.md — Classical Error Correction',
)
