"""Card: cz_07_05_volumetric_1_e_boundary_8d7f447d

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/05_modern_benchmarking.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_05_volumetric_1_e_boundary_8d7f447d',
    category='Cloze',
    front='Volumetric 1/e boundary:  w · d ≈ ______',
    back='w · d ≈ 2/ε  ·  Source: docs/07_quantum_hardware/05_modern_benchmarking.md — Modern Benchmarking: Mirror Circuits, XEB, and Layer Fidelity',
)
