"""Card: cz_01_04_symplectic_form_7b01b50f

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_symplectic_form_7b01b50f',
    category='Cloze',
    front="Symplectic form:  ω((x|z), (x'|z')) = ______",
    back="ω((x|z), (x'|z')) = x·z' + z·x' mod 2  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing",
)
