"""Card: cz_05_04_stabilizer_code_space_47cf5a5a

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/04_stabilizer_formalism.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_04_stabilizer_code_space_47cf5a5a',
    category='Cloze',
    front='Stabilizer code space:  V_S = ______',
    back='V_S = {|ψ⟩ : g|ψ⟩ = +|ψ⟩ for all g ∈ S}  ·  Source: docs/05_quantum_error_correction/04_stabilizer_formalism.md — The Stabilizer Formalism',
)
