"""Card: cz_09_01_amplitude_encoding_88b1859f

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/01_data_encoding.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_01_amplitude_encoding_88b1859f',
    category='Cloze',
    front='Amplitude encoding:  |φ(x)⟩ = ______',
    back='|φ(x)⟩ = ‖x‖^{-1} Σ_k x_k|k⟩  ·  Source: docs/09_quantum_machine_learning/01_data_encoding.md — Data Encoding and Quantum Feature Maps',
)
