"""Card: cz_07_04_rb_decay_4e059060

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/04_benchmarking_and_characterization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_04_rb_decay_4e059060',
    category='Cloze',
    front='RB decay:  P(|0⟩|m) = ______',
    back='P(|0⟩|m) = A p^m + B  ·  Source: docs/07_quantum_hardware/04_benchmarking_and_characterization.md — Benchmarking and Characterization of Quantum Hardware',
)
