"""Card: cz_09_02_geometric_difference_6a45c0c4

Generated by tools/gen_cloze.py from docs/09_quantum_machine_learning/02_quantum_kernels.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_09_02_geometric_difference_6a45c0c4',
    category='Cloze',
    front='Geometric difference:  g(K_C, K_Q) = ______',
    back='g(K_C, K_Q) = ‖√K_Q K_C^{-1} √K_Q‖_∞^{1/2}  ·  Source: docs/09_quantum_machine_learning/02_quantum_kernels.md — Quantum Kernel Methods',
)
