"""Card: cz_04_04_phase_estimation_setup_40f04c7e

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/04_quantum_phase_estimation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_04_phase_estimation_setup_40f04c7e',
    category='Cloze',
    front='Phase estimation setup:  U|u⟩ = ______',
    back='U|u⟩ = e^{2πiφ}|u⟩  ·  Full entry: U|u⟩ = e^{2πiφ}|u⟩,  φ ∈ [0,1)  ·  Source: docs/04_quantum_algorithms/04_quantum_phase_estimation.md — Quantum Phase Estimation',
)
