"""Card: cz_04_09_continuous_time_walk_f68f56e1

Generated by tools/gen_cloze.py from docs/04_quantum_algorithms/09_quantum_walks.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_04_09_continuous_time_walk_f68f56e1',
    category='Cloze',
    front='Continuous-time walk:  |ψ(t)⟩ = ______',
    back='|ψ(t)⟩ = e^{-iAt}|ψ(0)⟩  ·  Source: docs/04_quantum_algorithms/09_quantum_walks.md — Quantum Walks',
)
