"""Card: cz_05_07_concatenated_code_logical_ra_8565896a

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/07_fault_tolerance.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_07_concatenated_code_logical_ra_8565896a',
    category='Cloze',
    front='Concatenated code logical rate:  p_l ≈ ______',
    back='p_l ≈ (1/C)(Cp)^{2^l}  ·  Source: docs/05_quantum_error_correction/07_fault_tolerance.md — Fault-Tolerant Quantum Computation',
)
