"""Card: cz_07_02_lamb_dicke_parameter_12d2d5d8

Generated by tools/gen_cloze.py from docs/07_quantum_hardware/02_trapped_ion_qubits.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_07_02_lamb_dicke_parameter_12d2d5d8',
    category='Cloze',
    front='Lamb-Dicke parameter:  η = ______',
    back='η = k x₀ = k √(ℏ/(2mω))  ·  Source: docs/07_quantum_hardware/02_trapped_ion_qubits.md — Trapped Ion Qubits',
)
