"""Card: cz_01_04_pauli_group_cc05296a

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_pauli_group_cc05296a',
    category='Cloze',
    front='Pauli group:  |P_n| = ______',
    back='|P_n| = 4^{n+1}  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
