"""Card: cz_01_04_gf_4_a9de5a11

Generated by tools/gen_cloze.py from docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_01_04_gf_4_a9de5a11',
    category='Cloze',
    front='GF(4):  ω² = ______',
    back='ω² = ω + 1  ·  Source: docs/01_mathematical_foundations/04_groups_and_abstract_algebra.md — Groups and Abstract Algebra for Quantum Computing',
)
