"""Card: cz_08_03_hubbard_d6ea41e0

Generated by tools/gen_cloze.py from docs/08_advanced_topics/03_many_body_physics_and_simulation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_08_03_hubbard_d6ea41e0',
    category='Cloze',
    front='Hubbard:  H = ______',
    back='H = -t Σ (c†ᵢσ cⱼσ + h.c.) + U Σ nᵢ↑nᵢ↓  ·  Source: docs/08_advanced_topics/03_many_body_physics_and_simulation.md — Many-Body Physics and Quantum Simulation',
)
