"""Card: cz_05_06_stabilizers_84f45f8e

Generated by tools/gen_cloze.py from docs/05_quantum_error_correction/06_surface_code.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_05_06_stabilizers_84f45f8e',
    category='Cloze',
    front='Stabilizers:  B_f = ______',
    back='B_f = ⊗_{j ∈ ∂f} Z_j  ·  Source: docs/05_quantum_error_correction/06_surface_code.md — The Surface Code',
)
