"""Card: cz_10_01_diagonal_slater_condon_2e9e3bee

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/01_second_quantization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_01_diagonal_slater_condon_2e9e3bee',
    category='Cloze',
    front='Diagonal Slater-Condon:  ⟨Φ|H|Φ⟩ = ______',
    back='⟨Φ|H|Φ⟩ = Σ_i h_ii + ½Σ_ij [(ii|jj) - (ij|ji)] + E_nuc  ·  Source: docs/10_quantum_chemistry/01_second_quantization.md — Second Quantization and the Electronic Structure Hamiltonian',
)
