"""Card: cz_10_03_active_space_core_folding_abba5c17

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_03_active_space_core_folding_abba5c17',
    category='Cloze',
    front="Active-space core folding:  h'_pq = ______",
    back="h'_pq = h_pq + Σ_{i∈core} [2(pq|ii) - (pi|iq)]  ·  Source: docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — Active Spaces, Ansätze and Chemical Accuracy",
)
