"""Card: cz_11_01_werner_fidelity_49d952d1

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_werner_fidelity_49d952d1',
    category='Cloze',
    front='Werner fidelity:  F = ______',
    back='F = (1+3W)/4  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
