"""Card: cz_10_03_vqe_shot_cost_a0527d22

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_03_vqe_shot_cost_a0527d22',
    category='Cloze',
    front='VQE shot cost:  S ≈ ______',
    back='S ≈ (λ/ε)²  ·  Source: docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — Active Spaces, Ansätze and Chemical Accuracy',
)
