"""Card: cz_11_01_zero_capacity_loss_7ca0953d

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_zero_capacity_loss_7ca0953d',
    category='Cloze',
    front='Zero-capacity loss:  η ≤ ______',
    back='η ≤ 1/2  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
