"""Card: cz_10_04_qpe_readout_b65d3ed8

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/04_beyond_vqe.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_04_qpe_readout_b65d3ed8',
    category='Cloze',
    front='QPE readout:  E = ______',
    back='E = 2πk/(2^m t) - Δ  ·  Source: docs/10_quantum_chemistry/04_beyond_vqe.md — Beyond VQE: Phase Estimation, Qubitization and Real Resource Estimates',
)
