"""Card: cz_10_01_chemist_integral_4043f476

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/01_second_quantization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_01_chemist_integral_4043f476',
    category='Cloze',
    front='Chemist integral:  (pq|rs) = ______',
    back='(pq|rs) = ∫∫ χ_p*(1)χ_q(1) r₁₂⁻¹ χ_r*(2)χ_s(2)  ·  Source: docs/10_quantum_chemistry/01_second_quantization.md — Second Quantization and the Electronic Structure Hamiltonian',
)
