"""Card: cz_10_02_encoding_matrix_d32a2b1a

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/02_qubit_mappings.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_02_encoding_matrix_d32a2b1a',
    category='Cloze',
    front='Encoding matrix:  q = ______',
    back='q = β n (mod 2)  ·  Source: docs/10_quantum_chemistry/02_qubit_mappings.md — Fermion-to-Qubit Mappings and Qubit Tapering',
)
