"""Card: cz_10_03_orbital_rotation_54f58a79

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_03_orbital_rotation_54f58a79',
    category='Cloze',
    front='Orbital rotation:  κ = ______',
    back='κ = -κᵀ  ·  Source: docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — Active Spaces, Ansätze and Chemical Accuracy',
)
