"""Card: cz_11_01_swapping_a2d36057

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_swapping_a2d36057',
    category='Cloze',
    front='Swapping:  F_N = ______',
    back='F_N = (1 + 3W^N)/4  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
