"""Card: cz_10_03_chemical_accuracy_c6819301

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_03_chemical_accuracy_c6819301',
    category='Cloze',
    front='Chemical accuracy:  1 kcal/mol = ______',
    back='1 kcal/mol = 1.5936 mHa = 43.5 meV  ·  Source: docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — Active Spaces, Ansätze and Chemical Accuracy',
)
