"""Card: cz_11_02_bbpssw_werner_input_q_1_f_3_9672e346

Generated by tools/gen_cloze.py from docs/11_quantum_networking/02_repeaters_and_distillation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_02_bbpssw_werner_input_q_1_f_3_9672e346',
    category='Cloze',
    front="BBPSSW (Werner input, q = (1-F)/3):  F' = ______",
    back="F' = (F² + q²)/p  ·  Source: docs/11_quantum_networking/02_repeaters_and_distillation.md — Quantum Repeaters and Entanglement Distillation",
)
