"""Card: cz_10_03_k_upccgsd_count_9ccbfdee

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_03_k_upccgsd_count_9ccbfdee',
    category='Cloze',
    front='k-UpCCGSD count:  k·M(M-1) = ______',
    back='k·M(M-1) = O(kM²)  ·  Source: docs/10_quantum_chemistry/03_active_spaces_and_ansatze.md — Active Spaces, Ansätze and Chemical Accuracy',
)
