"""Card: cz_10_04_hamiltonian_1_norm_35b6986e

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/04_beyond_vqe.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_04_hamiltonian_1_norm_35b6986e',
    category='Cloze',
    front='Hamiltonian 1-norm:  λ = ______',
    back='λ = Σ_j|c_j|  ·  Source: docs/10_quantum_chemistry/04_beyond_vqe.md — Beyond VQE: Phase Estimation, Qubitization and Real Resource Estimates',
)
