"""Card: cz_11_03_telegate_fidelity_fd81fb76

Generated by tools/gen_cloze.py from docs/11_quantum_networking/03_distributed_quantum_computing.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_03_telegate_fidelity_fd81fb76',
    category='Cloze',
    front='Telegate fidelity:  F_ebit = ______',
    back='F_ebit = (5 F_avg - 1)/4  ·  Source: docs/11_quantum_networking/03_distributed_quantum_computing.md — Distributed Quantum Computing',
)
