"""Card: cz_11_01_two_photon_barrett_kok_heral_30d37caa

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_two_photon_barrett_kok_heral_30d37caa',
    category='Cloze',
    front='Two-photon (Barrett-Kok) heralding:  p = ______',
    back='p = ½ η_arm²  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
