"""Card: cz_11_01_single_photon_heralding_1aa6ff21

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_single_photon_heralding_1aa6ff21',
    category='Cloze',
    front='Single-photon heralding:  p ≈ ______',
    back='p ≈ 2 α_e η_arm  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
