"""Card: cz_11_02_pair_cost_4ba2a552

Generated by tools/gen_cloze.py from docs/11_quantum_networking/02_repeaters_and_distillation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_02_pair_cost_4ba2a552',
    category='Cloze',
    front='Pair cost:  c_k = ______',
    back='c_k = 2 c_{k-1}/p_k  ·  Source: docs/11_quantum_networking/02_repeaters_and_distillation.md — Quantum Repeaters and Entanglement Distillation',
)
