"""Card: cz_10_02_jordan_wigner_ca2f2b2f

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/02_qubit_mappings.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_02_jordan_wigner_ca2f2b2f',
    category='Cloze',
    front='Jordan-Wigner:  n̂_j = ______',
    back='n̂_j = (I - Z_j)/2  ·  Source: docs/10_quantum_chemistry/02_qubit_mappings.md — Fermion-to-Qubit Mappings and Qubit Tapering',
)
