"""Card: cz_10_01_second_quantized_hamiltonian_da3fef3c

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/01_second_quantization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_01_second_quantized_hamiltonian_da3fef3c',
    category='Cloze',
    front='Second-quantized Hamiltonian:  H = ______',
    back='H = Σ_pq h_pq a_p† a_q + (1/2) Σ_pqrs (pq|rs) a_p† a_r† a_s a_q + E_nuc  ·  Source: docs/10_quantum_chemistry/01_second_quantization.md — Second Quantization and the Electronic Structure Hamiltonian',
)
