"""Card: cz_11_01_fibre_transmittance_b23aba76

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_fibre_transmittance_b23aba76',
    category='Cloze',
    front='Fibre transmittance:  η(L) = ______',
    back='η(L) = 10^{-αL/10}  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
