"""Card: cz_11_02_midpoint_advantage_e1fe6d7a

Generated by tools/gen_cloze.py from docs/11_quantum_networking/02_repeaters_and_distillation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_02_midpoint_advantage_e1fe6d7a',
    category='Cloze',
    front='Midpoint advantage:  η(L) = ______',
    back='η(L) = √η(2L)  ·  Source: docs/11_quantum_networking/02_repeaters_and_distillation.md — Quantum Repeaters and Entanglement Distillation',
)
