"""Card: cz_10_01_electronic_hamiltonian_first_c4be27f9

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/01_second_quantization.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_01_electronic_hamiltonian_first_c4be27f9',
    category='Cloze',
    front='Electronic Hamiltonian (first quantized, atomic units):  H = ______',
    back='H = -Σ_i ∇²_i/2 - Σ_{iA} Z_A/|r_i - R_A| + Σ_{i<j} 1/r_ij  ·  Source: docs/10_quantum_chemistry/01_second_quantization.md — Second Quantization and the Electronic Structure Hamiltonian',
)
