"""Card: cz_11_02_dejmps_377f666e

Generated by tools/gen_cloze.py from docs/11_quantum_networking/02_repeaters_and_distillation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_02_dejmps_377f666e',
    category='Cloze',
    front='DEJMPS:  N = ______',
    back='N = (A+B)² + (C+D)² = p_success  ·  Source: docs/11_quantum_networking/02_repeaters_and_distillation.md — Quantum Repeaters and Entanglement Distillation',
)
