"""Card: cz_11_02_3_db_rule_3g_9d20d022

Generated by tools/gen_cloze.py from docs/11_quantum_networking/02_repeaters_and_distillation.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_02_3_db_rule_3g_9d20d022',
    category='Cloze',
    front='3 dB rule (3G):  L_max = ______',
    back='L_max = 3/α  ·  Source: docs/11_quantum_networking/02_repeaters_and_distillation.md — Quantum Repeaters and Entanglement Distillation',
)
