"""Card: cz_10_02_commutation_test_00c0746f

Generated by tools/gen_cloze.py from docs/10_quantum_chemistry/02_qubit_mappings.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_10_02_commutation_test_00c0746f',
    category='Cloze',
    front="Commutation test:  ⟨(x|z),(x'|z')⟩ = ______",
    back="⟨(x|z),(x'|z')⟩ = x·z' + z·x' mod 2  ·  Source: docs/10_quantum_chemistry/02_qubit_mappings.md — Fermion-to-Qubit Mappings and Qubit Tapering",
)
