"""Card: cz_11_01_linear_optics_bsm_47dfccaf

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_linear_optics_bsm_47dfccaf',
    category='Cloze',
    front='Linear-optics BSM:  p_max = ______',
    back='p_max = 1/2  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
