"""Card: cz_11_01_waiting_time_n_parallel_link_b308ce89

Generated by tools/gen_cloze.py from docs/11_quantum_networking/01_entanglement_distribution.md — do not edit by hand.
"""
from __future__ import annotations
from core.models import Flashcard

CARD = Flashcard(
    id='cz_11_01_waiting_time_n_parallel_link_b308ce89',
    category='Cloze',
    front='Waiting time, n parallel links:  H_n = ______',
    back='H_n = Σ_{k=1}^{n} 1/k  ·  Source: docs/11_quantum_networking/01_entanglement_distribution.md — Entanglement Distribution',
)
