"""Derivation: the parameter-shift rule.

Identity dE/dθ = [E(θ+π/2) − E(θ−π/2)]/2 verified numerically for random
observable/state with generator P satisfying P² = I.
"""
from __future__ import annotations
from core.models import Derivation, Step

DERIVATION = Derivation(
    id="deriv_param_shift",
    title="The Parameter-Shift Rule",
    goal=(
        "Derive the exact gradient formula dE/dθ = [E(θ+π/2) − E(θ−π/2)]/2 for "
        "Pauli-generated variational gates."
    ),
    steps=[
        Step(
            step_id="s1",
            prompt=(
                "Set the stage: a variational circuit contains a gate "
                "U(θ) = exp(−iθP/2) with P a Pauli string, and we measure "
                "E(θ) = ⟨ψ|U†(θ) H U(θ)|ψ⟩ (the rest of the circuit is absorbed into "
                "|ψ⟩ and H). What special algebraic property of P makes everything "
                "tractable, and what does it imply for the matrix form of U(θ)?"
            ),
            expected=(
                "P² = I (Pauli strings are involutory, eigenvalues ±1). Splitting the "
                "exponential series into even and odd powers then collapses it: "
                "U(θ) = cos(θ/2) I − i sin(θ/2) P."
            ),
            hint=(
                "What is P² for a Pauli string? Then group the Taylor series of the "
                "exponential by parity of the power."
            ),
            model_step=(
                "Every Pauli string P satisfies P² = I (each factor squares to I). "
                "Hence in exp(−iθP/2) = Σₖ(−iθ/2)ᵏPᵏ/k!, even powers give I and odd "
                "powers give P, and the series reassembles into\n"
                "U(θ) = cos(θ/2) I − i sin(θ/2) P —\n"
                "a 'rotation' with period 4π generated by P. This two-term form is the "
                "engine of the whole derivation."
            ),
        ),
        Step(
            step_id="s2",
            prompt=(
                "Insert U(θ) = cos(θ/2)I − i sin(θ/2)P into E(θ) and expand. Show that "
                "E(θ) = A + B cos θ + C sin θ, and identify A, B, C as θ-independent "
                "expectation values."
            ),
            expected=(
                "U†HU = cos²(θ/2) H + sin²(θ/2) PHP + i sin(θ/2)cos(θ/2)(PH − HP). "
                "Using cos² = (1+cos)/2, sin² = (1−cos)/2, 2 sin cos = sin: "
                "E(θ) = ⟨H+PHP⟩/2 + ⟨H−PHP⟩/2·cosθ + (i/2)⟨[P,H]⟩·sinθ. Essential "
                "point: E is exactly a FIRST-harmonic trigonometric function of θ."
            ),
            hint=(
                "Expand the product of the three factors, then use the double-angle "
                "identities to convert θ/2 terms into cosθ and sinθ."
            ),
            model_step=(
                "E(θ) = ⟨ψ|[cos(θ/2)I + i sin(θ/2)P] H [cos(θ/2)I − i sin(θ/2)P]|ψ⟩\n"
                "= cos²(θ/2)⟨H⟩ + sin²(θ/2)⟨PHP⟩ + i sin(θ/2)cos(θ/2)⟨PH − HP⟩.\n"
                "With the double-angle identities:\n"
                "E(θ) = A + B cosθ + C sinθ, where A = ⟨H + PHP⟩/2, B = ⟨H − PHP⟩/2, "
                "C = (i/2)⟨[P, H]⟩ (real, since i[P,H] is Hermitian). No higher "
                "harmonics appear — a single Pauli-generated angle always produces a "
                "pure sinusoid in the cost."
            ),
        ),
        Step(
            step_id="s3",
            prompt=(
                "Differentiate the form E(θ) = A + B cosθ + C sinθ, then evaluate the "
                "symmetric combination E(θ + π/2) − E(θ − π/2). Compare the two "
                "results."
            ),
            expected=(
                "E′(θ) = −B sinθ + C cosθ. Angle addition at shift π/2: "
                "E(θ±π/2) = A ∓ B sinθ ± C cosθ, so E(θ+π/2) − E(θ−π/2) = "
                "−2B sinθ + 2C cosθ = 2E′(θ)."
            ),
            hint=(
                "cos(θ ± π/2) = ∓sinθ and sin(θ ± π/2) = ±cosθ."
            ),
            model_step=(
                "E′(θ) = −B sinθ + C cosθ. Using cos(θ±π/2) = ∓sinθ, "
                "sin(θ±π/2) = ±cosθ:\n"
                "E(θ+π/2) = A − B sinθ + C cosθ, E(θ−π/2) = A + B sinθ − C cosθ,\n"
                "so E(θ+π/2) − E(θ−π/2) = −2B sinθ + 2C cosθ = 2E′(θ). The A term "
                "cancels; the shifted difference is EXACTLY twice the derivative."
            ),
        ),
        Step(
            step_id="s4",
            prompt=(
                "State the parameter-shift rule and explain why it is exact — not a "
                "finite-difference approximation — and why that matters on a quantum "
                "computer where E can only be estimated from shots."
            ),
            expected=(
                "dE/dθ = [E(θ+π/2) − E(θ−π/2)]/2, exact for all θ. Exact because E "
                "contains only the first harmonic (step 2); there are no higher-order "
                "terms for a finite difference to truncate. Practically: both "
                "evaluations are ordinary cost measurements at macroscopically shifted "
                "angles, so the estimator is unbiased and does not require a small step "
                "size that would amplify shot noise (variance ∝ 1/s² as s → 0 for "
                "naive finite differences)."
            ),
            hint=(
                "Contrast with [E(θ+s) − E(θ−s)]/(2s) for tiny s under shot noise of "
                "fixed size per evaluation."
            ),
            model_step=(
                "Parameter-shift rule: dE/dθ = ½[E(θ + π/2) − E(θ − π/2)] — an exact "
                "identity (verified numerically for random H, |ψ⟩), valid at every θ. "
                "Exactness comes from structure, not limits: E is a pure first "
                "harmonic, and shifting by ±π/2 turns cosθ ↔ ∓sinθ, implementing "
                "differentiation algebraically. On hardware this matters enormously: "
                "each term is a standard expectation estimated from shots, the "
                "estimator is unbiased, and because the shift is O(1) the noise is NOT "
                "amplified — whereas a naive finite difference [E(θ+s)−E(θ−s)]/(2s) "
                "with small s divides fixed-size shot noise by s, blowing up the "
                "variance like 1/s². (The general-shift version "
                "[E(θ+s)−E(θ−s)]/(2 sin s) shows π/2 also minimises the variance.)"
            ),
        ),
        Step(
            step_id="s5",
            prompt=(
                "Scope and limits: for which gates does this rule apply directly, what "
                "changes for generators with eigenvalues other than ±1, and how is a "
                "full circuit gradient assembled?"
            ),
            expected=(
                "Direct: any gate exp(−iθP/2) with involutory generator (all Pauli "
                "rotations RX, RY, RZ, RZZ, …). Other generators: if the generator has "
                "more than two distinct eigenvalues the cost has several harmonics and "
                "one needs generalised/multi-term shift rules (more shifted "
                "evaluations), or gate decomposition; two eigenvalues {λ₊,λ₋} rescale "
                "the shift. Full gradient: apply the rule parameter by parameter — 2 "
                "circuit evaluations per parameter, all independent/parallelisable."
            ),
            hint=(
                "The derivation leaned on P² = I giving exactly one harmonic. What if "
                "the generator's spectrum is richer? And how many evaluations for m "
                "parameters?"
            ),
            model_step=(
                "The rule applies verbatim to every gate generated by an involutory "
                "operator — all single- and multi-qubit Pauli rotations, the workhorses "
                "of VQE/QAOA ansätze. If the generator G has eigenvalue gaps other "
                "than 2 (e.g. controlled rotations, or number operators in bosonic "
                "circuits), E(θ) contains several harmonics — one frequency per "
                "distinct eigenvalue gap — and exact gradients need generalised shift "
                "rules with more evaluation points (one pair per frequency), "
                "stochastic shift rules, or decomposing the gate into Pauli "
                "rotations. For a circuit with m parameters, the gradient costs 2m "
                "cost-function evaluations, each an independent job — embarrassingly "
                "parallel, and the basis of gradient-based VQA training."
            ),
        ),
    ],
)
